/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.91
 * Generated at: 2024-11-28 06:09:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.reports;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import com.ConnectionProvider;
import java.text.*;

public final class detailed_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


Connection con=null;
ResultSet rs=null;
Statement stmt=null;
Statement stmt2=null;
String query="";
String e;
int count;

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(7);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.text");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.ConnectionProvider");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write(" \n");
      out.write("\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("\n");
      out.write("function params(){\n");
      out.write("var vid1 = document.getElementById(\"state\").value\n");
      out.write("var vid2 =document.getElementById(\"district\").value\n");
      out.write("var vid3 =document.getElementById(\"location\").value\n");
      out.write("\n");
      out.write("var vfdate= document.getElementById(\"fdate\").value\n");
      out.write("var vtdate= document.getElementById(\"tdate\").value\n");
      out.write("        var vfhr= document.getElementById(\"fhr\").value	\n");
      out.write("	var vfmin= document.getElementById(\"fmin\").value\n");
      out.write("	var vthr= document.getElementById(\"thr\").value\n");
      out.write("	var vtmin= document.getElementById(\"tmin\").value\n");
      out.write("window.location.replace(\"detailed.jsp?value1=\"+vid1+\"&&value2=\"+vid2+\"&&value3=\"+vid3+\"&&vfdate=\"+vfdate+\"&&vtdate=\"+vtdate+\"&&fhr=\"+vfhr+\"&&fmin=\"+vfmin+\"&&thr=\"+vthr+\"&&tmin=\"+vtmin);\n");
      out.write("}\n");
      out.write("\n");
      out.write("// Quick and simple export target #table_id into a csv\n");
      out.write("function download_table_as_csv(tblCustomers, separator = ',') {\n");
      out.write("    // Select rows from table_id\n");
      out.write("    var rows = document.querySelectorAll('table#' +tblCustomers + ' tr');\n");
      out.write("    // Construct csv\n");
      out.write("    var csv = [];\n");
      out.write("    for (var i = 0; i < rows.length; i++) {\n");
      out.write("        var row = [], cols = rows[i].querySelectorAll('td, th');\n");
      out.write("        for (var j = 0; j < cols.length; j++) {\n");
      out.write("            // Clean innertext to remove multiple spaces and jumpline (break csv)\n");
      out.write("            var data = cols[j].innerText.replace(/(\\r\\n|\\n|\\r)/gm, '').replace(/(\\s\\s)/gm, ' ')\n");
      out.write("            // Escape double-quote with double-double-quote (see https://stackoverflow.com/questions/17808511/properly-escape-a-double-quote-in-csv)\n");
      out.write("            data = data.replace(/\"/g, '\"\"');\n");
      out.write("            // Push escaped string\n");
      out.write("            row.push('\"' + data + '\"');\n");
      out.write("        }\n");
      out.write("        csv.push(row.join(separator));\n");
      out.write("    }\n");
      out.write("    var csv_string = csv.join('\\n');\n");
      out.write("    // Download it\n");
      out.write("    var filename = 'AWS Detailed_' + new Date().toLocaleDateString() + '.csv';\n");
      out.write("    var link = document.createElement('a');\n");
      out.write("    link.style.display = 'none';\n");
      out.write("    link.setAttribute('target', '_blank');\n");
      out.write("    link.setAttribute('href', 'data:text/csv;charset=utf-8,' + encodeURIComponent(csv_string));\n");
      out.write("    link.setAttribute('download', filename);\n");
      out.write("    document.body.appendChild(link);\n");
      out.write("    link.click();\n");
      out.write("    document.body.removeChild(link);\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("\n");
      out.write('\n');

String value1=request.getParameter("value1");
String value2=request.getParameter("value2");
String value3=request.getParameter("value3");
String vfdate=request.getParameter("vfdate");
String vtdate=request.getParameter("vtdate");
	String vfhr=request.getParameter("fhr");
	String vfmin=request.getParameter("fmin");
	String vthr=request.getParameter("thr");
	String vtmin=request.getParameter("tmin");



if (value1==null){value1="0";}
if (value2==null){value2="0";}
if (value3==null){value3="0";}

DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
String formattedDate = df.format(new java.util.Date());

if(vfdate == null){ 
 vfdate=formattedDate;
 vtdate=formattedDate;
 vfhr="00";
 vfmin="00";
 vthr="00";
 vtmin="00";
}

con = ConnectionProvider.getCon();
stmt=con.createStatement();
stmt2=con.createStatement();
rs = stmt.executeQuery("select param_id as sid,group_value as state from parameter where active='Y' and group_family='LOCATION' and Group_name='STATE'");

      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<link href=\"../../styles/text.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("<script type=\"text/javascript\" src=\"../../Script/datepicker.js\"></script>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write(".export {\n");
      out.write("  border: 2px solid black;\n");
      out.write("  background-color: white;\n");
      out.write("  color: black;\n");
      out.write("  padding: 5px 15px;\n");
      out.write("  font-size: 15px;\n");
      out.write("  font-family:Georgia;\n");
      out.write("   font-weight: bold;\n");
      out.write("  margin-bottom:3px;\n");
      out.write("  cursor: pointer;\n");
      out.write("}\n");
      out.write("/* Green */\n");
      out.write(".success {\n");
      out.write("  border-color: black;\n");
      out.write(" \n");
      out.write("  color: white;\n");
      out.write("  background-color: #4d4dff;\n");
      out.write("  opacity:0.8;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".success:hover {\n");
      out.write("  background-color: #99ff99;\n");
      out.write("  color: black;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- export to excel script start-->\n");
      out.write("<script type=\"text/javascript\" src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js\"></script>\n");
      out.write(" <script src=\"../../Script/table2excel.js\" type=\"text/javascript\"></script>\n");
      out.write(" <script type=\"text/javascript\">\n");
      out.write("        function Export() {\n");
      out.write("            $(\"#tblCustomers\").table2excel({\n");
      out.write("				filename: \"Detailed_Data :\"+ new Date().toLocaleString().replace(/[\\-\\:\\.]/g, \" \") + \".xls\"\n");
      out.write("            });\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("<!-- export to excel script end-->\n");
      out.write("\n");
      out.write("\n");
      out.write("<table width=\"100%\" border=\"1\" cellpadding=\"1\"  bgcolor=\"#DBEBFF\" VALIGN=TOP>\n");
      out.write("<tr><td width=\"10%\" VALIGN=TOP>\n");
      out.write("<table width=\"10%\" border=\"1\" cellpadding=\"1\"  bgcolor=\"#DBEBFF\" VALIGN=TOP>\n");
      out.write("\n");
      out.write("<!--   date selection starts here -->\n");
      out.write("\n");
      out.write("\n");
      out.write("<tr><td class=\"Blue-content\" colspan=\"4\"><b>Select Date Range</b></td></tr>\n");
      out.write("<tr><td class=\"content style1\" align=\"right\"><b>From</b></td>\n");
      out.write("<td>\n");
      out.write(" <input id=\"fdate\"  class=\"content style1\" type=\"text\" name=\"fdate\" size=\"10\" maxlength=\"12\" value=");
      out.print(vfdate);
      out.write(">\n");
      out.write("<a href=\"javascript:NewCal('fdate','ddmmyyyy',false)\"><img src=\"../../images/calendar.JPG\" width=\"16\" height=\"16\" border=\"0\" alt=\"Pick a date\"></a>\n");
      out.write("<select id=\"fhr\" class=\"content style1\">\n");
 for (int i=0; i<24; i++) {
	e=Integer.toString(i);
	if (e.length()==1){e="0"+e;}
      out.write("\n");
      out.write("<option value=\"");
      out.print(e);
      out.write('"');
      out.write('>');
      out.print(e);
      out.write("</option>\n");
}
      out.write("\n");
      out.write("<option value=");
      out.print(vfhr);
      out.write(" selected disabled>");
      out.print(vfhr);
      out.write("</option>\n");
      out.write("</select><a class=\"content style1\">Hr</a>\n");
      out.write("<select id=\"fmin\" class=\"content style1\">\n");
 	for (int i=0; i<60; i++) {
		e=Integer.toString(i);
		if (e.length()==1){e="0"+e;}
      out.write("\n");
      out.write("<option value=\"");
      out.print(e);
      out.write('"');
      out.write('>');
      out.print(e);
      out.write("</option>\n");
}
      out.write("\n");
      out.write("<option value=");
      out.print(vfmin);
      out.write(" selected disabled>");
      out.print(vfmin);
      out.write("</option>\n");
      out.write("</select><a class=\"content style1\">Mi</a>\n");
      out.write("</td>\n");
      out.write("\n");
      out.write("</td>\n");
      out.write("</tr>\n");
      out.write("<tr><td class=\"content style1\" align=\"right\"><b>To</b></td>\n");
      out.write("<td><input id=\"tdate\"  class=\"content style1\" type=\"text\" name=\"tdate\" size=\"10\" maxlength=\"12\" value=");
      out.print(vtdate);
      out.write(">\n");
      out.write("<a href=\"javascript:NewCal('tdate','ddmmyyyy',false)\"><img src=\"../../images/calendar.JPG\" width=\"16\" height=\"16\" border=\"0\" alt=\"Pick a date\"></a>\n");
      out.write("<select id=\"thr\" class=\"content style1\">\n");
 for (int i=0; i<24; i++) {
	e=Integer.toString(i);
	if (e.length()==1){e="0"+e;}
      out.write("\n");
      out.write("<option value=\"");
      out.print(e);
      out.write('"');
      out.write('>');
      out.print(e);
      out.write("</option>\n");
}
      out.write("\n");
      out.write("<option value=");
      out.print(vthr);
      out.write(" selected disabled>");
      out.print(vthr);
      out.write("</option>\n");
      out.write("</select><a class=\"content style1\">Hr</a>\n");
      out.write("<select id=\"tmin\" class=\"content style1\">\n");
 	for (int i=0; i<60; i++) {
		e=Integer.toString(i);
		if (e.length()==1){e="0"+e;}
      out.write("\n");
      out.write("<option value=\"");
      out.print(e);
      out.write('"');
      out.write('>');
      out.print(e);
      out.write("</option>\n");
}
      out.write("\n");
      out.write("<option value=");
      out.print(vtmin);
      out.write(" selected disabled>");
      out.print(vtmin);
      out.write("</option>\n");
      out.write("</select><a class=\"content style1\">Mi</a>\n");
      out.write("</td>\n");
      out.write("</tr>\n");
      out.write("\n");
      out.write(" <!-- date selection Ends here -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<tr><td class=\"Blue-content\" colspan=\"6\" align=\"left\">Select Station</td></tr>\n");
      out.write("<tr><td class=\"content style1\"><b> State </b></td>\n");
      out.write("<td>\n");
      out.write("<select id=\"state\" onchange=\"params()\" class=\"content style1\">\n");
      out.write("<option value=\"0\">--Please Select--</option>\n");
 while(rs.next()){ 
      out.write("\n");
      out.write("<option value=\"");
      out.print(rs.getInt("sid"));
      out.write('"');
      out.write('>');
      out.print(rs.getString("state"));
      out.write("</option>\n");
      out.write("\n");
 if(rs.getString("sid").equals(value1)){
      out.write("\n");
      out.write("<option value=\"");
      out.print(value1);
      out.write("\" selected disabled>");
      out.print(rs.getString("state"));
      out.write("</option> \n");

}

}

      out.write("\n");
      out.write("</select> </td></tr>\n");
      out.write("<tr><td class=\"content style1\"><b> District</b> </td><td>\n");
      out.write("<select id=\"district\" onchange=\"params()\" class=\"content style1\">\n");
      out.write("<option value=\"0\">--Please Select--</option>\n");
      out.write("<option value=\"-1\">All</option>\n");
      out.write("\n");

rs=stmt.executeQuery("select param_id as did,group_value as district from parameter where active='Y' and group_family='LOCATION' and Group_name='DISTRICT' and parent_group='"+value1+"' order by group_value");

while(rs.next()){

      out.write("\n");
      out.write("<option value=\"");
      out.print(rs.getInt("did"));
      out.write('"');
      out.write(' ');
      out.write('>');
      out.print(rs.getString("district"));
      out.write("</option>\n");
 if(rs.getString("did").equals(value2)){
      out.write("\n");
      out.write("<option value=\"");
      out.print(value2);
      out.write("\" selected disabled>");
      out.print(rs.getString("district"));
      out.write("</option>\n");


}
}

      out.write("\n");
      out.write("</select>\n");
      out.write("</td></tr>\n");
      out.write("<!-- add location  start ---->\n");
      out.write("<tr><td class=\"content style1\"><b> Location</b> </td><td>\n");
      out.write("<select id=\"location\" onchange=\"params()\" class=\"content style1\">\n");
      out.write("<option value=\"0\">--Please Select--</option>\n");
      out.write("<option value=\"-1\">All</option>\n");
      out.write("\n");

rs=stmt.executeQuery("select location from station_configs_det where district='"+value2+"'");

while(rs.next()){

      out.write("\n");
      out.write("<option value=\"");
      out.print(rs.getString("location"));
      out.write('"');
      out.write(' ');
      out.write('>');
      out.print(rs.getString("location"));
      out.write("</option>\n");
 if(rs.getString("location").equals(value3)){
      out.write("\n");
      out.write("<option value=\"");
      out.print(value3);
      out.write("\" selected disabled>");
      out.print(rs.getString("location"));
      out.write("</option>\n");


}
}

      out.write("\n");
      out.write("</select>\n");
      out.write("</td></tr>\n");
      out.write("<!-- Add location end--->\n");
      out.write("</table>\n");
      out.write("</td>\n");
      out.write("<td valign=top>\n");
      out.write("<!----\n");
      out.write("<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" id=\"stretch\" > \n");
      out.write("	<tr><td class=\"Headings\" align=\"center\">Detailed Data 8:30AM - 8:30AM</td></tr>\n");
      out.write("\n");
      out.write("---->\n");
      out.write("<table width=\"100%\" border=\"1\" cellpadding=\"0\" cellspacing=\"0\"  >\n");
      out.write("	<tr>\n");
      out.write("	\n");
      out.write("<td align=\"right\"bgcolor=\"#cce0fb\" >\n");
      out.write("\n");
      out.write("<input type=\"image\" src=\"../../images/excel.jpg\" height=\"70%\">\n");
      out.write("<button class=\"export success\" value=\"Export\" onclick=\"Export()\" > Export</button>&nbsp\n");
      out.write("<button class=\"export success\"  onclick=\"download_table_as_csv('tblCustomers');\" >Csv</button>&nbsp\n");
      out.write("\n");
      out.write("</td>\n");
      out.write("\n");
      out.write("\n");
      out.write("</tr>\n");
      out.write("\n");
      out.write("<table id=\"tblCustomers\" width=\"100%\" border=\"1\" cacellpadding=\"0\" cellspacing=\"0\" id=\"stretch\" > \n");
      out.write("	<tr><td class=\"Headings\" align=\"center\" colspan=9 width=\"80%\">All Data Detailed</td></tr>\n");
      out.write("	<tr><td class=\"Blue-content\" align=\"center\" colspan=9 width=\"80%\"> from ");
      out.print(vfdate);
      out.write(' ');
      out.print(vfhr);
      out.write(':');
      out.print(vfmin);
      out.write(" Hrs to ");
      out.print(vtdate);
      out.write(' ');
      out.print(vthr);
      out.write(':');
      out.print(vtmin);
      out.write(" Hrs</td></tr>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!--<tr><td><table width=\"100%\" border=\"1\" cellpadding=\"0\" cellspacing=\"0\" id=\"stretch\" > -->\n");
      out.write("<tr class=\"Blue-content\" align=\"center\">\n");
      out.write("<td rowspan=\"2\">Client ID</td>\n");
      out.write("<td rowspan=\"2\">District</td>\n");
      out.write("<!--<td rowspan=\"2\">Mandal</td>-->\n");
      out.write("<td rowspan=\"2\">Location</td>\n");
      out.write("<td rowspan=\"2\">Date Time</td>\n");
      out.write("<!-- <td>Latitude</td> <td>Longitude</td> -->\n");
      out.write("<td rowspan=\"2\"> Water_height(m)</td>\n");
      out.write("<td rowspan=\"2\">Waterdedpth_air(m)</td>\n");
      out.write("\n");
      out.write("<td rowspan=\"2\">Water_Pressure<br>(&nbsp;milibar&nbsp;)</td>\n");
      out.write("<!--<td rowspan=\"2\">Air_Pressure<br>(&nbsp;milibar&nbsp;)</td>--> \n");
      out.write("<td rowspan=\"2\">Battery<br>voltage</td>\n");
      out.write("<td rowspan=\"2\">Signal<br>Strength</td>\n");
      out.write("\n");
      out.write("</tr>\n");
      out.write("<tr  class=\"Blue-content\" align=\"center\">\n");
      out.write("\n");
      out.write("\n");
      out.write("</tr>\n");
      out.write("\n");

query="select dp.clientid,to_char(packet_date,'dd/mm/yyyy hh24:mi:ss') as date,scd.longitude,scd.latitude,scd.location,scd.state,coalesce((select group_value from parameter where param_id=county),'-') as county,par.group_value,";
//query+="(case when temp < 0 then null else temp end) as temp,(case when temp_min < 0 then null else temp_min end) as temp_min,(case when temp_max < 0 then null else temp_max end) as temp_max,";
//query+="(case when humidity_avg < 0 then null else humidity_avg end) as humidity_avg,(case when humidity < 0 then null else humidity end) as humidity,";
//query+="(case when wind_direction < 0 then null else wind_direction end) as wind_direction_avg,(case when gust_direction < 0 then null else gust_direction end) as gust_direction,";
//query+="(case when wind_min < 0 then null else wind_min end) as wind_min,(case when wind < 0 then null else wind end) as wind,(case when wind_max < 0 then null else wind_max end) as wind_max,(case when wind_avg < 0 then null else wind_avg end) as wind_avg,(case when gust < 0 then null else gust end) as gust, ";
query+="(case when water_height < 0 then null else water_height end) as water_height,(case when waterdepth_air < 0 then null else waterdepth_air end) as waterdepth_air, ";

query+="(case when water_pressure < 0 then null else water_pressure end) as water_pressure,(case when air_pressure < 0 then null else air_pressure end) as air_pressure,battery,signal_strength ";
//query+=" dp.*, (case when temp < 0 then null else temp end) temp1";
query+=" from data_packets as dp, (select clientid,longitude,latitude,location,state,district,county from station_configs_det) as scd ,";
query+="(select param_id,group_value from parameter) as par where packet_type='D' ";
query+="and packet_date >= to_timestamp('"+vfdate+","+vfhr+":"+vfmin+"','dd/mm/yyyy,hh24:mi:ss') and packet_date <= to_timestamp('"+vtdate+","+vthr+":"+vtmin+"','dd/mm/yyyy,hh24:mi:ss') ";
query+="and dp.clientid=scd.clientid and par.param_id=scd.district";

if(value2.equalsIgnoreCase("-1")) {	query=query+" and state='"+value1+"'";  }
	else{ query=query+" and district='"+value2+"' and location='"+value3+"'";}

query=query+" order by date,clientid";
// rs=stmt.executeQuery(query);


//out.println(query);
	rs=stmt.executeQuery(query);
	while(rs.next()){

      out.write("\n");
      out.write("<tr  class=\"readonly\">\n");
      out.write("<td>");
      out.print(rs.getString("clientid"));
      out.write("</td><td>");
      out.print(rs.getString("group_value"));
      out.write("\n");
      out.write("<!--</td><td>");
      out.print(rs.getString("county"));
      out.write("</td> -->\n");
      out.write("<td>");
      out.print(rs.getString("location"));
      out.write("</td><td>");
      out.print(rs.getString("date"));
      out.write("</td>\n");
      out.write("<!-- <td>");
      out.print(rs.getString("latitude"));
      out.write("</td> <td>");
      out.print(rs.getString("longitude"));
      out.write("</td> -->\n");
 if (rs.getString("water_height")==null){ 
      out.write("<td align=\"right\">NA </td>");
} else {
      out.write("<td align=\"right\">");
      out.print(rs.getDouble("water_height"));
      out.write("</td>");
}
      out.write('\n');
 if (rs.getString("waterdepth_air")==null){ 
      out.write("<td align=\"right\">NA</td>");
} else {
      out.write("<td align=\"right\">");
      out.print(rs.getDouble("waterdepth_air"));
      out.write("</td>");
}
      out.write('\n');
 if (rs.getString("water_pressure")==null){ 
      out.write("<td align=\"right\">NA </td>");
} else {
      out.write("<td align=\"right\">");
      out.print(rs.getDouble("water_pressure"));
      out.write("</td>");
}
      out.write("\n");
      out.write("<!--");
 if (rs.getString("air_pressure")==null){ 
      out.write("<td align=\"right\">NA </td>");
} else {
      out.write("<td align=\"right\">");
      out.print(rs.getDouble("air_pressure"));
      out.write("</td>");
}
      out.write("-->\n");
      out.write("\n");
 if (rs.getString("battery")==null){ 
      out.write("<td align=\"right\">N/A</td>");
} else {
      out.write("<td align=\"right\">");
      out.print(rs.getDouble("battery"));
      out.write("</td>");
}
      out.write('\n');
 if (rs.getString("signal_strength")==null){ 
      out.write("<td align=\"right\">N/A</td>");
} else {
      out.write("<td align=\"right\">");
      out.print(rs.getDouble("signal_strength"));
      out.write("</td>");
}
      out.write("\n");
      out.write("\n");
      out.write("</tr>\n");

}

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</tr></table>\n");
      out.write("\n");
      out.write("</table>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("	</table>\n");
      out.write("</td></tr>\n");
      out.write("</table>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
