/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.91
 * Generated at: 2024-10-17 07:07:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.*;
import java.text.*;
import java.util.*;
import com.locationDao;
import com.locationBean;

public final class location_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(8);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.text");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("com.locationDao");
    _jspx_imports_classes.add("com.locationBean");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      com.locationBean obj = null;
      obj = (com.locationBean) _jspx_page_context.getAttribute("obj", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (obj == null){
        obj = new com.locationBean();
        _jspx_page_context.setAttribute("obj", obj, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("obj"), request);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
 
//Sesssion Management
if(null == session.getAttribute("theName")){  
   response.sendRedirect("timeout.jsp");
}

      out.write("\r\n");
      out.write("\r\n");

Integer oid	= (Integer) session.getAttribute("theOid");

String state=request.getParameter("state");
String dist=request.getParameter("dist");
String county=request.getParameter("county");

if (state==null){state="0";}
if (dist==null){dist="0";}
if (county==null){county="0";}

int vstateid=Integer.parseInt(state);
int vdistid=Integer.parseInt(dist);
//int vcountyid=Integer.parseInt(county);

String lid=request.getParameter("lid");
String act=request.getParameter("act");
locationDao location = new locationDao();





      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link href=\"../styles/text.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"../Script/datepicker.js\"></script>\r\n");
      out.write("<BODY bgcolor=\"#DBEBFF\">\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function params(){\r\n");
      out.write("	var vid1 = document.getElementById(\"state\").value;\r\n");
      out.write("	var vid2 =document.getElementById(\"dist\").value;\r\n");
      out.write("	var vid3 =document.getElementById(\"county\").value;\r\n");
      out.write("	//alert(vid1);\r\n");
      out.write("	window.location.replace(\"location.jsp?state=\"+vid1+\"&&dist=\"+vid2+\"&&county=\"+vid3);\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
 if ("Add".equalsIgnoreCase(act)){ 
      out.write("\r\n");
      out.write("<form name=\"FrmAddloc\" action=\"location.jsp\" method=\"post\">\r\n");
      out.write("<table width=\"100%\" border=\"0\" cellpadding=\"1\" >\r\n");
      out.write("<tr>\r\n");
      out.write("			<td  align=\"right\" colspan=\"2\">\r\n");
      out.write("			<button type=\"submit\" class=\"button-image\" name=\"act\" value=\"Insert\"> <img src=\"../images/icon_save.png\"  height=\"30\" width=\"30\" alt=\"Add\" /></button>\r\n");
      out.write("			<button type=\"submit\" class=\"button-image\" name=\"act\" value=\"Edit\"> <img src=\"../images/icon_edit.png\"  height=\"30\" width=\"30\" alt=\"Add\" /></button>\r\n");
      out.write("			<button type=\"submit\" class=\"button-image\" name=\"act\" value=\"Delete\"> <img src=\"../images/icon_delete.png\"  height=\"30\" width=\"30\" alt=\"Add\" /></button>\r\n");
      out.write("			</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr><td width=\"10%\" VALIGN=TOP>\r\n");
      out.write("	<table width=\"100%\" class=\"border\"  cellpadding=\"1\" >\r\n");
      out.write("	<tr><td class=\"Blue-content\" colspan=\"6\" align=\"left\">Select</td></tr>\r\n");
      out.write("	<tr><td class=\"label\"><b> State </b></td>\r\n");
      out.write("		<td><select id=\"state\" name=state onchange=\"params()\" class=\"content style1\">\r\n");
      out.write("			<option value=\"0\">--Please Select--</option>\r\n");
      out.write("			");
 
			List<locationBean> list1 =location.viewStates();
			Iterator<locationBean> S = list1.iterator(); 
			while (S.hasNext()) {
			obj = (locationBean)S.next();
			
      out.write("\r\n");
      out.write("			<option value=\"");
      out.print(obj.getStateid());
      out.write('"');
      out.write('>');
      out.print(obj.getSname());
      out.write("</option>\r\n");
      out.write("			");
 if(obj.getStateid()==vstateid){
      out.write("\r\n");
      out.write("			<option value=\"");
      out.print(vstateid);
      out.write("\" selected >");
      out.print(obj.getSname());
      out.write("</option> \r\n");
      out.write("						");
} 
								}
      out.write("\r\n");
      out.write("			</select> </td>\r\n");
      out.write("	<td class=\"label\"><b> District</b> </td>\r\n");
      out.write("		<td><select id=\"dist\" name=dist onchange=\"params()\" class=\"content style1\">\r\n");
      out.write("			<option value=\"0\">--Please Select--</option>\r\n");
      out.write("			");
 
			List<locationBean> list2 =location.viewDistrict(vstateid);
			Iterator<locationBean> D = list2.iterator(); 
			while (D.hasNext()) {
			obj = (locationBean)D.next();
			
      out.write("\r\n");
      out.write("			<option value=\"");
      out.print(obj.getDistrict_id());
      out.write('"');
      out.write(' ');
      out.write('>');
      out.print(obj.getDname());
      out.write("</option>\r\n");
      out.write("			");
 if(obj.getDistrict_id()==vdistid){
      out.write("\r\n");
      out.write("			<option value=\"");
      out.print(vdistid);
      out.write("\" selected >");
      out.print(obj.getDname());
      out.write("</option>\r\n");
      out.write("			");
}
					}
      out.write("\r\n");
      out.write("		</select></td>\r\n");
      out.write("		<td class=\"label\"><b> Mandal</b> </td>\r\n");
      out.write("		<td><select id=\"county\" name=county onchange=\"\" class=\"content style1\">\r\n");
      out.write("		<option value=\"0\">--Please Select--</option>\r\n");
      out.write("			");

			List<locationBean> list3 =location.viewCounty(vdistid);
			Iterator<locationBean> C = list3.iterator(); 
			while (C.hasNext()) {
				obj = (locationBean)C.next();
			
      out.write("\r\n");
      out.write("		<option value=\"");
      out.print(obj.getCounty_id());
      out.write('"');
      out.write(' ');
      out.write('>');
      out.print(obj.getCname());
      out.write("</option>\r\n");
      out.write("		");
 	}
      out.write("\r\n");
      out.write("		</select>\r\n");
      out.write("		</td></tr>\r\n");
      out.write("	</table> \r\n");
      out.write("	</td></tr>\r\n");
      out.write("	<tr><td Align=\"center\">\r\n");
      out.write("	<table width=\"75%\" border=\"0\" cellpadding=\"0\" cellspacing=\"5\" id=\"stretch\" > \r\n");
      out.write("		<tr class=\"label\"><td width=\"10%\">Location</td><td><input type=\"text\" class=\"content style1\" size=\"50\" id=\"txtName\" name=txtName value=\"\" /></td></tr>\r\n");
      out.write("		<tr><td class=\"label\">Latitude</td><td><input type=\"text\" class=\"content style1\" id=\"txtlat\" size=\"10\" name=txtLat value=\"0\" /></td></tr>\r\n");
      out.write("		<tr><td class=\"label\">Longitude</td><td><input type=\"text\" class=\"content style1\" id=\"txtLong\" size=\"10\" name=txtLong value=\"0\" /></td></tr>\r\n");
      out.write("		<tr><td class=\"label\">Altitude</td><td><input type=\"text\" class=\"content style1\" id=\"txtAlt\" size=\"10\" name=txtAlt value=\"0\" /></td></tr>\r\n");
      out.write("	</table>\r\n");
      out.write("	</td></tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
} else if ("Edit".equalsIgnoreCase(act)){ 
		if (lid==null){ 
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("	alert(\"no record selected!\");\r\n");
      out.write("	 history.go(-1);\r\n");
      out.write("	</script>\r\n");
      out.write("	");
} else { 
	
	obj.setLocation_id(Integer.parseInt(lid));
	locationDao loc = new locationDao();
	loc.searchLocation(obj);
	int Location_id=obj.getLocation_id();
	String Lname=obj.getLname();
	vstateid=obj.getStateid();
	vdistid=obj.getDistrict_id();
	//vcountyid=obj.getCounty_id();
	String Lat = obj.getLat();
	String Lon = obj.getLon();
	String Alt = obj.getAlt();
	
      out.write("\r\n");
      out.write("<form name=\"FrmEditloc\" action=\"location.jsp\" method=\"post\">\r\n");
      out.write("<input type=\"hidden\" name=\"lid\" value=\"");
      out.print(Location_id);
      out.write("\" />\r\n");
      out.write("\r\n");
      out.write("<table width=\"100%\" border=\"0\" cellpadding=\"1\" >\r\n");
      out.write("<tr>\r\n");
      out.write("			<td  align=\"right\" colspan=\"2\">\r\n");
      out.write("			<button type=\"submit\" class=\"button-image\" name=\"act\" value=\"Update\"> <img src=\"../images/icon_save.png\"  height=\"30\" width=\"30\" alt=\"Add\" /></button>\r\n");
      out.write("			<button type=\"submit\" class=\"button-image\" name=\"act\" value=\"Edit\"> <img src=\"../images/icon_edit.png\"  height=\"30\" width=\"30\" alt=\"Add\" /></button>\r\n");
      out.write("			<button type=\"submit\" class=\"button-image\" name=\"act\" value=refresh> <img src=\"../images/icon_refresh.png\"  height=\"30\" width=\"30\" alt=\"reset\" /></button>\r\n");
      out.write("			</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr><td width=\"10%\" VALIGN=TOP>\r\n");
      out.write("	<table width=\"100%\" class=\"border\"  cellpadding=\"1\" >\r\n");
      out.write("	<tr><td class=\"Blue-content\" colspan=\"6\" align=\"left\">Select</td></tr>\r\n");
      out.write("	<tr><td class=\"label\"><b> State </b></td>\r\n");
      out.write("		<td><select id=\"state\" name=state onchange=\"params()\" class=\"content style1\">\r\n");
      out.write("			<option value=\"0\">--Please Select--</option>\r\n");
      out.write("			");
 
			List<locationBean> list1 =location.viewStates();
			Iterator<locationBean> S = list1.iterator(); 
			while (S.hasNext()) {
			obj = (locationBean)S.next();
			
      out.write("\r\n");
      out.write("			<option value=\"");
      out.print(obj.getStateid());
      out.write('"');
      out.write('>');
      out.print(obj.getSname());
      out.write("</option>\r\n");
      out.write("			");
 if(obj.getStateid()==vstateid){
      out.write("\r\n");
      out.write("			<option value=\"");
      out.print(vstateid);
      out.write("\" selected >");
      out.print(obj.getSname());
      out.write("</option> \r\n");
      out.write("							");
						} 
								}
      out.write("\r\n");
      out.write("			</select> </td>\r\n");
      out.write("	<td class=\"label\"><b> District</b> </td>\r\n");
      out.write("		<td><select id=\"dist\" name=dist onchange=\"params()\" class=\"content style1\">\r\n");
      out.write("			<option value=\"0\">--Please Select--</option>\r\n");
      out.write("			");
 
			List<locationBean> list2 =location.viewDistrict(vstateid);
			Iterator<locationBean> D = list2.iterator(); 
			while (D.hasNext()) {
			obj = (locationBean)D.next();
			
      out.write("\r\n");
      out.write("			<option value=\"");
      out.print(obj.getDistrict_id());
      out.write('"');
      out.write(' ');
      out.write('>');
      out.print(obj.getDname());
      out.write("</option>\r\n");
      out.write("			");
 if(obj.getDistrict_id()==vdistid){
      out.write("\r\n");
      out.write("			<option value=\"");
      out.print(vdistid);
      out.write("\" selected >");
      out.print(obj.getDname());
      out.write("</option>\r\n");
      out.write("			");
}
					}
      out.write("\r\n");
      out.write("			</select></td><td class=\"label\"><b> Mandal</b> </td>\r\n");
      out.write("		<td><select id=\"county\" name=county class=\"content style1\">\r\n");
      out.write("		<option value=\"0\">--Please Select--</option>\r\n");
      out.write("			");

			List<locationBean> list3 =location.viewCounty(vdistid);
			Iterator<locationBean> C = list3.iterator(); 
			while (C.hasNext()) {
				obj = (locationBean)C.next();
			
      out.write("\r\n");
      out.write("		<option value=\"");
      out.print(obj.getCounty_id());
      out.write('"');
      out.write(' ');
      out.write('>');
      out.print(obj.getCname());
      out.write("</option>\r\n");
      out.write("		");
 	}
      out.write("\r\n");
      out.write("		</select>\r\n");
      out.write("		</td></tr>\r\n");
      out.write("	</table> \r\n");
      out.write("	</td></tr>\r\n");
      out.write("	<tr><td Align=\"center\">\r\n");
      out.write("	<table width=\"75%\" border=\"0\" cellpadding=\"0\" cellspacing=\"5\" id=\"stretch\" > \r\n");
      out.write("		<tr class=\"label\"><td width=\"10%\">Location</td><td><input type=\"text\" class=\"content style1\" size=\"50\" id=\"txtName\" name=txtName value=\"");
      out.print(Lname);
      out.write("\" /></td></tr>\r\n");
      out.write("		<tr><td class=\"label\">Latitude</td><td><input type=\"text\" class=\"content style1\" id=\"txtlat\" size=\"10\" name=txtLat value=\"");
      out.print(Lat);
      out.write("\" /></td></tr>\r\n");
      out.write("		<tr><td class=\"label\">Longitude</td><td><input type=\"text\" class=\"content style1\" id=\"txtLong\" size=\"10\" name=txtLong value=\"");
      out.print(Lon);
      out.write("\" /></td></tr>\r\n");
      out.write("		<tr><td class=\"label\">Altitude</td><td><input type=\"text\" class=\"content style1\" id=\"txtAlt\" size=\"10\" name=txtAlt value=\"");
      out.print(Alt);
      out.write("\" /></td></tr>\r\n");
      out.write("	</table>\r\n");
      out.write("	</td></tr>\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
}
	} else if ("mAdd".equalsIgnoreCase(act)){ 
				
		String Vmandal = request.getParameter("txtMandal");
		if ((Vmandal == null)||("".equalsIgnoreCase(Vmandal))){ }
		else {	location.addCounty(request.getParameter("txtMandal"),vdistid); }
	
	
      out.write("\r\n");
      out.write("	<form name=\"FrmAddMandal\" action=\"location.jsp\" method=\"post\">\r\n");
      out.write("	<table width=\"100%\" border=\"0\" cellpadding=\"2\" >\r\n");
      out.write("	\r\n");
      out.write("	<tr><td width=\"10%\" VALIGN=TOP>\r\n");
      out.write("	<table width=\"80%\" class=\"border\"  cellpadding=\"1\">\r\n");
      out.write("	<tr><td class=\"label\"><b> State</b></td><td class=\"label\"><b> District</b></td><td class=\"label\"><b> Mandal</b></td></tr>\r\n");
      out.write("	<tr><td valign=\"top\"><select id=\"state\" name=state onchange=\"params()\" class=\"content style1\">\r\n");
      out.write("			<option value=\"0\">--Please Select--</option>\r\n");
      out.write("			");
 
			List<locationBean> list1 =location.viewStates();
			Iterator<locationBean> S = list1.iterator(); 
			while (S.hasNext()) {
			obj = (locationBean)S.next();
			
      out.write("\r\n");
      out.write("			<option value=\"");
      out.print(obj.getStateid());
      out.write('"');
      out.write('>');
      out.print(obj.getSname());
      out.write("</option>\r\n");
      out.write("			");
 if(obj.getStateid()==vstateid){
      out.write("\r\n");
      out.write("			<option value=\"");
      out.print(vstateid);
      out.write("\" selected>");
      out.print(obj.getSname());
      out.write("</option> \r\n");
      out.write("							");
						} 
								}
      out.write("\r\n");
      out.write("			</select> \r\n");
      out.write("			</td>\r\n");
      out.write("	<td valign=\"top\"> \r\n");
      out.write("	<select id=\"dist\" name=dist onchange=\"params()\" class=\"content style1\">\r\n");
      out.write("			<option value=\"0\">--Please Select--</option>\r\n");
      out.write("			");
 
			List<locationBean> list2 =location.viewDistrict(vstateid);
			Iterator<locationBean> D = list2.iterator(); 
			while (D.hasNext()) {
			obj = (locationBean)D.next();
			
      out.write("\r\n");
      out.write("			<option value=\"");
      out.print(obj.getDistrict_id());
      out.write('"');
      out.write(' ');
      out.write('>');
      out.print(obj.getDname());
      out.write("</option>\r\n");
      out.write("			");
 if(obj.getDistrict_id()==vdistid){
      out.write("\r\n");
      out.write("			<option value=\"");
      out.print(vdistid);
      out.write("\" selected >");
      out.print(obj.getDname());
      out.write("</option>\r\n");
      out.write("			");
}
					}
      out.write("\r\n");
      out.write("			</select>\r\n");
      out.write("			</td>\r\n");
      out.write("		\r\n");
      out.write("			<td> \r\n");
      out.write("			<td>\r\n");
      out.write("			<select id=\"county\" name=county  size=\"26\" style=\"width: 140px;\" class=\"content style1\">\r\n");
      out.write("			");

			List<locationBean> list3 =location.viewCounty(vdistid);
			Iterator<locationBean> C = list3.iterator(); 
			while (C.hasNext()) {
				obj = (locationBean)C.next();
			
      out.write("\r\n");
      out.write("			<option value=\"");
      out.print(obj.getCounty_id());
      out.write('"');
      out.write(' ');
      out.write('>');
      out.print(obj.getCname());
      out.write("</option>\r\n");
      out.write("			");
 	}
      out.write("\r\n");
      out.write("			</select></td>\r\n");
      out.write("		<tr><td class=\"label\" > Mandal </td><td><input class=\"Blue-content\" type=text name=\"txtMandal\" size=\"30\"  maxlength=\"50\" >\r\n");
      out.write("			<button type=\"submit\" class=\"button-image\" name=\"act\" value=\"mAdd\"> <img src=\"../images/icon_save.png\"  height=\"30\" width=\"30\" alt=\"Mandal Add\" /></button>\r\n");
      out.write("			\r\n");
      out.write("		</tr>\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("	</table>		\r\n");
      out.write("	</table>\r\n");
      out.write("	</form>\r\n");
      out.write("		\r\n");
} else if (act==null || ("".equalsIgnoreCase(act))||("Search".equalsIgnoreCase(act)) ||("Update".equalsIgnoreCase(act)) || ("Cancel".equalsIgnoreCase(act))||
	("Insert".equalsIgnoreCase(act))||("Delete".equalsIgnoreCase(act))){
		if ("Insert".equalsIgnoreCase(act)){
			obj.setLname(request.getParameter("txtName"));
            obj.setLat(request.getParameter("txtLat"));
            obj.setLon(request.getParameter("txtLong"));
            obj.setAlt(request.getParameter("txtAlt"));
            obj.setStateid(vstateid);
            obj.setDistrict_id(vdistid);
            //obj.setCounty_id(vcountyid);
			//location.addLocation(obj);
			}	
		if ("Delete".equalsIgnoreCase(act)){
					if (lid==null){ 
      out.write("\r\n");
      out.write("					<script>\r\n");
      out.write("						alert(\"no record selected!\");\r\n");
      out.write("						history.go(-1);\r\n");
      out.write("					</script>\r\n");
      out.write("				");
 } else {
				int id=Integer.parseInt(lid);
				location.delLocation(id);} 
			}
		
		if ("Update".equalsIgnoreCase(act)){
			int id=Integer.parseInt(lid);
			obj.setLocation_id(id);
			obj.setLname(request.getParameter("txtName"));
            obj.setLat(request.getParameter("txtLat"));
            obj.setLon(request.getParameter("txtLong"));
            obj.setAlt(request.getParameter("txtAlt"));
            obj.setStateid(vstateid);
            obj.setDistrict_id(vdistid);
            //obj.setCounty_id(vcountyid);
			
			}
		

      out.write("	\r\n");
      out.write("<form name=\"Frmlistloc\" action=\"location.jsp\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("	<table  width=\"80%\"  align=\"center\" cellpadding=\"0\" >\r\n");
      out.write("	<tr><td>&nbsp;</td></tr>\r\n");
      out.write("	<tr><td class=\"label\"><b> State</b></td><td class=\"label\"><b> District</b></td><td class=\"label\"><b> Mandal</b>\r\n");
      out.write("	");
 if (vdistid!=0){ 
      out.write("\r\n");
      out.write("			<button type=\"submit\" class=\"button-image\" name=\"act\" value=\"mAdd\"> <img src=\"../images/icon_add.png\"  height=\"20\" width=\"20\" alt=\"State Add\" /></button>\r\n");
      out.write("			");
}
      out.write("\r\n");
      out.write("	</td></tr>\r\n");
      out.write("	<tr><td VALIGN=TOP>\r\n");
      out.write("			<select id=\"state\" name=state onchange=\"params()\" class=\"content style1\">\r\n");
      out.write("			<option value=\"0\">--Please Select--</option>\r\n");
      out.write("			");
 
			List<locationBean> list1 =location.viewStates();
			Iterator<locationBean> S = list1.iterator(); 
			while (S.hasNext()) {
			obj = (locationBean)S.next();
			
      out.write("\r\n");
      out.write("			<option value=\"");
      out.print(obj.getStateid());
      out.write('"');
      out.write('>');
      out.print(obj.getSname());
      out.write("</option>\r\n");
      out.write("			");
 if(obj.getStateid()==vstateid){
      out.write("\r\n");
      out.write("			<option value=\"");
      out.print(vstateid);
      out.write("\" selected>");
      out.print(obj.getSname());
      out.write("</option> \r\n");
      out.write("							");
						} 
								}
      out.write("\r\n");
      out.write("			</select> \r\n");
      out.write("		</td>\r\n");
      out.write("		<td VALIGN=TOP>\r\n");
      out.write("	 		<select id=\"dist\" name=dist onchange=\"params()\" class=\"content style1\">\r\n");
      out.write("			<option value=\"0\">--Please Select--</option>\r\n");
      out.write("			");
 
			List<locationBean> list2 =location.viewDistrict(vstateid);
			Iterator<locationBean> D = list2.iterator(); 
			while (D.hasNext()) {
			obj = (locationBean)D.next();
			
      out.write("\r\n");
      out.write("			<option value=\"");
      out.print(obj.getDistrict_id());
      out.write('"');
      out.write(' ');
      out.write('>');
      out.print(obj.getDname());
      out.write("</option>\r\n");
      out.write("			");
 if(obj.getDistrict_id()==vdistid){
      out.write("\r\n");
      out.write("			<option value=\"");
      out.print(vdistid);
      out.write("\" selected >");
      out.print(obj.getDname());
      out.write("</option>\r\n");
      out.write("			");
}
					}
      out.write("\r\n");
      out.write("			</select>\r\n");
      out.write("		</td>\r\n");
      out.write("		<td>\r\n");
      out.write("			<select id=\"county\" name=county  size=\"26\" style=\"width: 140px;\" class=\"content style1\">\r\n");
      out.write("			");

			List<locationBean> list3 =location.viewCounty(vdistid);
			Iterator<locationBean> C = list3.iterator(); 
			while (C.hasNext()) {
				obj = (locationBean)C.next();
			
      out.write("\r\n");
      out.write("			<option value=\"");
      out.print(obj.getCounty_id());
      out.write('"');
      out.write(' ');
      out.write('>');
      out.print(obj.getCname());
      out.write("</option>\r\n");
      out.write("			");
 	}
      out.write("\r\n");
      out.write("			</select>\r\n");
      out.write("			\r\n");
      out.write("		</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("	</table>\r\n");
      out.write("</form>\r\n");
}
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
