/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.91
 * Generated at: 2024-12-02 04:20:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.LoginDao;
import com.LoginBean;

public final class roles_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("com.LoginBean");
    _jspx_imports_classes.add("com.LoginDao");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      com.LoginBean obj = null;
      obj = (com.LoginBean) _jspx_page_context.getAttribute("obj", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (obj == null){
        obj = new com.LoginBean();
        _jspx_page_context.setAttribute("obj", obj, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("obj"), request);
      out.write("\r\n");
      out.write("\r\n");
      com.LoginBean objM = null;
      objM = (com.LoginBean) _jspx_page_context.getAttribute("objM", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (objM == null){
        objM = new com.LoginBean();
        _jspx_page_context.setAttribute("objM", objM, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("objM"), request);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

//Sesssion Management
if(null == session.getAttribute("theName")){  
   response.sendRedirect("timeout.jsp");
}

Integer oid	= (Integer) session.getAttribute("theOid");


	String act = request.getParameter("act"); 
	String vroleid = request.getParameter("txtRoleid");
	String vname = request.getParameter("txtName");
//	String vlist = request.getParameter("LstMenu");
	String vlist = request.getParameter("options");
//	out.println("vlist"+vlist);
	
	String vlname = request.getParameter("txtLName");
	String vpswd = request.getParameter("txtPswd");
	String vrole = request.getParameter("txtRole");
	String vphone = request.getParameter("txtPhone");
	String vemail = request.getParameter("txtEmail");
	String[] mymenus = request.getParameterValues("options");


	
 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link href=\"../styles/text.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("<title> Role Management </title>\r\n");
      out.write("<SCRIPT >\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</SCRIPT>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

Integer vid=0;
int DisRow=0;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
if (act==null || ("Update".equalsIgnoreCase(act)) || ("Cancel".equalsIgnoreCase(act))||("Insert".equalsIgnoreCase(act))||("Delete".equalsIgnoreCase(act))) {
	LoginDao arole = new LoginDao();
	if ("Update".equalsIgnoreCase(act)){
		arole.updateRole(Integer.parseInt(vroleid),vname,mymenus);
		}
			
	if ("Insert".equalsIgnoreCase(act)){
		arole.addRole(oid,vname,mymenus);
		}

	if ("Delete".equalsIgnoreCase(act)){
		if (vroleid!=null) {
			arole.delRole(Integer.parseInt(vroleid));	
		 } else { 
      out.write("\r\n");
      out.write("			<script> alert(\"no record selected!\"); \r\n");
      out.write("			history.go(-1);\r\n");
      out.write("			</script>\r\n");
      out.write("		");
}
		
	}

act="";

      out.write("\r\n");
      out.write("<form action=\"roles.jsp\" method=\"post\" name=\"frmrlist\" >\r\n");
      out.write("<table class=\"mytable\" >\r\n");
      out.write("	<tr>\r\n");
      out.write("			<td align=\"right\" colspan=\"7\">\r\n");
      out.write("			<button type=\"submit\" class=\"button-image\" id=\"act\" name=\"act\" value=\"Add\"> <img src=\"../images/icon_add.png\"  height=\"30\" width=\"30\" alt=\"Add\" /></button>  \r\n");
      out.write("			<button type=\"submit\" class=\"button-image\" id=\"act\" name=\"act\" value=\"Edit\" > <img src=\"../images/icon_edit.png\"  height=\"30\" width=\"30\" alt=\"Add\" /></button>\r\n");
      out.write("			<button type=\"submit\" class=\"button-image\" id=\"act\" name=\"act\" value=\"Delete\"> <img src=\"../images/icon_delete.png\"  height=\"30\" width=\"30\" alt=\"Delete\" /></button> \r\n");
      out.write("			</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<table class=\"mytable\">\r\n");
      out.write("<tr valign=\"top\"> \r\n");
      out.write("<td class=\"boxcontainer\">\r\n");
      out.write("<div class=\"\">\r\n");
      out.write("  <div class=\"titlebox\" id=\"\">\r\n");
      out.write("  <div class=\"titlebox-title\">\r\n");
      out.write("        <span class=\"left\">Roles List ");
 
      out.write("</span>\r\n");
      out.write("        \r\n");
      out.write("   \r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"titlebox-content \" id=\"t1\">\r\n");
      out.write("  <hr class=\"clear\" />\r\n");
      out.write("  <table class=\"ticket-list collection-as-table\">\r\n");
      out.write("  <tr class=\"collection-as-table\">\r\n");
      out.write("	<th class=\"collection-as-table\">#</th>\r\n");
      out.write("	<th class=\"collection-as-table\">Name</th>\r\n");
      out.write("	<th class=\"collection-as-table\">select</th>\r\n");
      out.write("	<th class=\"collection-as-table\">Menu(s) Assigned</th>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("			");

			LoginDao role = new LoginDao();
			List<LoginBean> list1 =role.listRoles(oid);
			Iterator<LoginBean> D = list1.iterator();
			int x =0;
			while (D.hasNext()) {
			obj = (LoginBean)D.next();
			x++;
			if ( (x%2) == 0 ) { 
      out.write("\r\n");
      out.write("			<tr class=\"evenline\" > ");
} else { 
      out.write("<tr class=\"oddline\" >  ");
}
      out.write("\r\n");
      out.write("			<td class=\"content style\">");
      out.print(x);
      out.write("</td> \r\n");
      out.write("			<td class=\"content style\">");
      out.print(obj.getRole_desc());
      out.write("</td>\r\n");
      out.write("			<td class=\"content style\"><input type=\"radio\" name=\"txtRoleid\" value=");
      out.print(obj.getRole_id());
      out.write("></td>\r\n");
      out.write("			<!-- menu listing -->\r\n");
      out.write("			<td>\r\n");
      out.write("			<table>\r\n");
      out.write("			");
 
			LoginDao module = new LoginDao();
			List<LoginBean> list2 =module.listMenu(Integer.parseInt(obj.getRole_id()));
			Iterator<LoginBean> M = list2.iterator(); 
			while (M.hasNext()) {
			objM = (LoginBean)M.next();						
			
      out.write("\r\n");
      out.write("				<tr ><td class=\"content style\">");
      out.print(objM.getModule());
      out.write("</td><tr>\r\n");
      out.write("				");
}
				
      out.write("\r\n");
      out.write("			</table>\r\n");
      out.write("			");
	  DisRow++;	}
				if(DisRow==0)
			{	/*To write to the server if the resultset is null*/
			
      out.write("\r\n");
      out.write("			<tr><th colspan=6 class=\"content style1\">No Records found</th></tr>\r\n");
      out.write("			");
} 
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
 } else if ("Add".equalsIgnoreCase(act)){ 	
      out.write("\r\n");
      out.write("<form action=\"roles.jsp\" method=\"post\" name=\"frmradd\" >\r\n");
      out.write("\r\n");
      out.write("<table class=\"mytable\" >\r\n");
      out.write("	<tr>\r\n");
      out.write("			<td align=\"right\" colspan=\"7\">\r\n");
      out.write("			<button type=\"submit\" class=\"button-image\" id=\"act\" name=\"act\" value=\"Insert\"> <img src=\"../images/icon_save.png\"  height=\"30\" width=\"30\" alt=\"Save\" /></button>  \r\n");
      out.write("			<button type=\"submit\" class=\"button-image\" id=\"act\" name=\"act\" value=\"Cancel\"> <img src=\"../images/icon_delete.png\"  height=\"30\" width=\"30\" alt=\"Cancel\" /></button> \r\n");
      out.write("			</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<table class=\"mytable\">\r\n");
      out.write("<tr valign=\"top\"><td class=\"boxcontainer\">\r\n");
      out.write("<div class=\"\">\r\n");
      out.write("  <div class=\"titlebox\" id=\"\">\r\n");
      out.write("  <div class=\"titlebox-title\">\r\n");
      out.write("        <span class=\"left\">");
      out.print(act);
      out.write(" Role</span>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"titlebox-content \" id=\"t1\">\r\n");
      out.write("  <hr class=\"clear\" />\r\n");
      out.write("  <table class=\"ticket-list collection-as-table\">\r\n");
      out.write("   <tr class=\"collection-as-table\">\r\n");
      out.write("			<tr><td class=\"Blue-content\">Role Name</td><td><input type=\"text\" name=\"txtName\" class=\"content style1\" value=\"\"> </td></tr>\r\n");
      out.write("			<tr><td class=\"Blue-content\">Menu List</td><td>\r\n");
      out.write("			");
 		
			LoginDao role = new LoginDao();
			List<LoginBean> list1 =role.listModules(oid);
			Iterator<LoginBean> D = list1.iterator(); 
			while (D.hasNext()) {
			obj = (LoginBean)D.next();
			
      out.write("\r\n");
      out.write("			  <input name=\"options\" type=\"checkbox\" value=\"");
      out.print(obj.getModule_id() );
      out.write("\" > ");
      out.print(obj.getModule());
      out.write("<BR>\r\n");
      out.write("			");
 }
      out.write("\r\n");
      out.write("			</td></tr>\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("		 \r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
} else if ("Edit".equalsIgnoreCase(act) ) { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<form action=\"roles.jsp\" method=\"post\" name=\"frmredit\" >\r\n");
      out.write("\r\n");
      out.write("<table class=\"mytable\" >\r\n");
      out.write("	<tr>\r\n");
      out.write("			<td align=\"right\" colspan=\"7\">\r\n");
      out.write("			<button type=\"submit\" class=\"button-image\" id=\"act\" name=\"act\" value=\"Update\"> <img src=\"../images/icon_save.png\"  height=\"30\" width=\"30\" alt=\"Save\" /></button>  \r\n");
      out.write("			<button type=\"submit\" class=\"button-image\" id=\"act\" name=\"act\" value=\"Cancel\"> <img src=\"../images/icon_delete.png\"  height=\"30\" width=\"30\" alt=\"Cancel\" /></button> \r\n");
      out.write("			</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<table class=\"mytable\">\r\n");
      out.write("<tr valign=\"top\"> \r\n");
      out.write("<td class=\"boxcontainer\">\r\n");
      out.write("<div class=\"\">\r\n");
      out.write("  <div class=\"titlebox\" id=\"\">\r\n");
      out.write("  <div class=\"titlebox-title\">\r\n");
      out.write("        <span class=\"left\">");
      out.print( act);
      out.write(" Role");
 
      out.write("</span>\r\n");
      out.write("        \r\n");
      out.write("   \r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"titlebox-content \" id=\"t1\">\r\n");
      out.write("  <hr class=\"clear\" />\r\n");
      out.write("  <table class=\"ticket-list collection-as-table\">\r\n");
      out.write("		");
	if (vroleid!=null){
			LoginDao role = new LoginDao();
			obj.setRole_id(vroleid);
			role.findRole(obj);
		
      out.write("\r\n");
      out.write("		<tr><td class=\"Blue-content\">Role ID</td><td><input type=\"text\" readonly name=\"txtRoleid\" class=\"content style1\" value=");
      out.print(obj.getRole_id());
      out.write(" ></td></tr>\r\n");
      out.write("		<tr><td class=\"Blue-content\">Role Name</td><td><input type=\"text\" name=\"txtName\" class=\"content style1\" value=\"");
      out.print(obj.getRole_desc());
      out.write("\"> </td></tr>\r\n");
      out.write("		<tr><td class=\"Blue-content\">Menu List</td><td>\r\n");
      out.write("		");

		//LoginDao role = new LoginDao();
		List<LoginBean> list1 =role.listRoleMenu(Integer.parseInt(vroleid));
		Iterator<LoginBean> D = list1.iterator(); 
		while (D.hasNext()) {
		obj = (LoginBean)D.next();
		if (obj.getMenu_url()!=null){ 
      out.write("\r\n");
      out.write("			  <INPUT name=\"options\" type=\"CHECKBOX\"  checked value=\"");
      out.print(obj.getModule_id());
      out.write('"');
      out.write('>');
      out.write(' ');
      out.print(obj.getModule());
      out.write("<BR>\r\n");
      out.write("			  ");
} else { 
      out.write("\r\n");
      out.write("			 <INPUT name=\"options\" type=\"checkbox\"   value=\"");
      out.print(obj.getModule_id());
      out.write('"');
      out.write('>');
      out.write(' ');
      out.print(obj.getModule());
      out.write("<BR>\r\n");
      out.write("			");
} }
      out.write("\r\n");
      out.write("			</td></tr> \r\n");
      out.write(" 	</table>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("			 ");
} else { 
      out.write("\r\n");
      out.write("				<script> alert(\"no record selected!\"); \r\n");
      out.write("				history.go(-1);\r\n");
      out.write("				</script>\r\n");
      out.write("			");
}
      out.write("\r\n");
      out.write("</form>\r\n");
} 
      out.write("\r\n");
      out.write("</body> \r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
