/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.91
 * Generated at: 2024-09-26 05:00:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import com.ConnectionProvider;

public final class dashboard_005fold_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


Connection con=null;
ResultSet rs=null;
Statement stmt=null; 


  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.ConnectionProvider");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0 Transitional//EN\">\n");
      out.write("\n");
      out.write("\n");
      out.write(" \n");
      out.write("\n");
      out.write('\n');

con = ConnectionProvider.getCon();
stmt=con.createStatement();

rs=stmt.executeQuery("select active_stations,reporting,(active_stations-reporting) as not_reporting  from (select count(1) as Active_stations from station_configs_det where activate!=0 ) active ,(select count(distinct(clientid)) as Reporting from data_packets as dp where packet_date >= CURRENT_TIMESTAMP - INTERVAL '12 Hours' and exists  (select 1 from station_configs_det as scd where activate!=0 and dp.clientid=scd.clientid ) ) Reporting");

Integer vTotal=0;
Integer vWorking=0;
Integer vFaulty=0;
int DisRow=0;
while(rs.next()){ 
	vTotal= rs.getInt(1) ;
	vWorking= rs.getInt(2) ;
	vFaulty= rs.getInt(3) ;
	DisRow++;
	}


String strXML ="<graph caption='Station Statistics' bgColor='F1f1f1' decimalPrecision='0' showPercentageValues='0' showNames='1' numberPrefix='' showValues='1' showPercentageInLabel='0' pieYScale='45' pieBorderAlpha='40' pieFillAlpha='70' pieSliceDepth='15' pieRadius='100'>";
strXML +="    <set value='"+vWorking+"' name='Reporting' color='FF9966'/>";
strXML +="    <set value='"+vFaulty+"' name='Faulty' color='FF0000'/>";
strXML +="</graph>";


      out.write('\n');
      out.write('\n');

con = ConnectionProvider.getCon();
stmt=con.createStatement();

rs=stmt.executeQuery("select active_stations,reporting,(active_stations-reporting) as not_reporting  from (select count(1) as Active_stations from station_configs_det where activate!=0 and address in('ARG')) active ,(select count(distinct(clientid)) as Reporting from data_packets as dp where packet_date >= CURRENT_TIMESTAMP - INTERVAL '12 Hours' and exists  (select 1 from station_configs_det as scd where activate!=0 and dp.clientid=scd.clientid and address in('ARG')) ) Reporting");

Integer vTotal1=0;
Integer vWorking1=0;
Integer vFaulty1=0;
int DisRow1=0;
while(rs.next()){ 
	vTotal1= rs.getInt(1) ;
	vWorking1= rs.getInt(2) ;
	vFaulty1= rs.getInt(3) ;
	DisRow++;
	}


String strXML1 ="<graph caption='Station Statistics' bgColor='F1f1f1' decimalPrecision='0' showPercentageValues='0' showNames='1' numberPrefix='' showValues='1' showPercentageInLabel='0' pieYScale='45' pieBorderAlpha='40' pieFillAlpha='70' pieSliceDepth='15' pieRadius='100'>";
strXML1 +="    <set value='"+vWorking1+"' name='Reporting' color='FF9966'/>";
strXML1 +="    <set value='"+vFaulty1+"' name='Faulty' color='FF0000'/>";
strXML1 +="</graph>";


      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<HTML>\n");
      out.write("<HEAD>\n");
      out.write("<TITLE> WMS Dash Board </TITLE>\n");
      out.write("<link href=\"../styles/text.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("<script>\n");
      out.write("/* Auto Refresh Page with Time script*/\n");
      out.write("\n");
      out.write("//enter refresh time in \"minutes:seconds\" Minutes should range from 0 to inifinity. Seconds should range from 0 to 59\n");
      out.write("var limit=\"2:00\"\n");
      out.write("\n");
      out.write("if (document.images){\n");
      out.write("var parselimit=limit.split(\":\")\n");
      out.write("parselimit=parselimit[0]*60+parselimit[1]*1\n");
      out.write("}\n");
      out.write("function beginrefresh(){\n");
      out.write("if (!document.images)\n");
      out.write("return\n");
      out.write("if (parselimit==1)\n");
      out.write("window.location.reload()\n");
      out.write("else{ \n");
      out.write("parselimit-=1\n");
      out.write("curmin=Math.floor(parselimit/60)\n");
      out.write("cursec=parselimit%60\n");
      out.write("if (curmin!=0)\n");
      out.write("curtime=curmin+\" minutes and \"+cursec+\" seconds left until page refresh!\"\n");
      out.write("else\n");
      out.write("curtime=cursec+\" seconds left until page refresh!\"\n");
      out.write("window.status=curtime\n");
      out.write("setTimeout(\"beginrefresh()\",1000)\n");
      out.write("}\n");
      out.write("}\n");
      out.write("\n");
      out.write("window.onload=beginrefresh\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</HEAD>\n");
      out.write("\n");
      out.write("<BODY>\n");
      out.write("\n");
      out.write("<!-- Sesssion Management -->\n");
if(null == session.getAttribute("theName")){  
  // User is not logged in.
  out.println("your Session has expired");
  response.sendRedirect("../timeout.jsp");
}

      out.write("\n");
      out.write("<!-- End of Sesssion Management -->\n");
      out.write("\n");
      out.write("<table width=\"100%\" class=border border=\"0\" cellpadding=\"0\" cellspacing=\"0\" id=\"stretch\" >\n");
      out.write("\n");
      out.write("<tr class=\"Blue-content\"  align=\"left\">\n");
      out.write("\n");
      out.write("<td>Station Statistics for AWS<br>(Last 12 Hours)</td>\n");
      out.write("<!--<td>Station Statistics for TRG<br>(Last 12 Hours)</td>-->\n");
      out.write("<td>Reporting stations for AWS<br>(Last 12 Hours) %</td>\n");
      out.write("<!--<td>Reporting stations for TRG<br>(Last 12 Hours) %</td>-->\n");
      out.write("\n");
      out.write("</tr>\n");
      out.write("<tr class=\"Blue-content\"  align=\"left\">\n");
      out.write("\n");
      out.write("<td>\n");
      out.write("	<OBJECT classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\" codebase=http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0\" width=\"200\" height=\"375\" id=\"Column3D\" >\n");
      out.write("	<param name=\"movie\" value=\"../../../FusionCharts/Charts/FCF_Pie3D.swf\" />\n");
      out.write("	<param name=\"FlashVars\" value=\"&dataURL=Data.xml&chartWidth=200&chartHeight=250\">\n");
      out.write("	<param name=\"quality\" value=\"high\" />\n");
      out.write("	<embed src=\"../../../FusionCharts/Charts/FCF_Pie3D.swf\" flashVars=\"&dataXML=");
      out.print(strXML);
      out.write("&chartWidth=250&chartHeight=200\" quality=\"high\" width=\"250\" height=\"250\" name=\"stats\" type=\"application/x-shockwave-flash\" pluginspage=\"http://www.macromedia.com/go/getflashplayer\" />\n");
      out.write("	</object>\n");
      out.write("	<table border=\"1\" cellpadding=\"1\" cellspacing=\"1\" class=\"border\">\n");
      out.write("	<tr><td><a href=\"stnlist.jsp?v1=t\" target=\"_blank\" class=\"Blue-content\">Total</td><td class=\"content style1\"><a href=\"stnlist.jsp?v1=t\" target=\"_blank\" class=\"Blue-content\">");
      out.print(vTotal);
      out.write("</td> </tr>\n");
      out.write("	<tr><td><a href=\"stnlist.jsp?v1=w\" target=\"_blank\" class=\"Blue-content\">Working</td><td class=\"content style1\"><a href=\"stnlist.jsp?v1=w\" target=\"_blank\" class=\"Blue-content\">");
      out.print(vWorking);
      out.write("</td> </tr>\n");
      out.write("	<tr><td><a href=\"stnlist.jsp?v1=n\" target=\"_blank\" class=\"Blue-content\">Not Working</td><td class=\"content style1\"><a href=\"stnlist.jsp?v1=n\" target=\"_blank\" class=\"Blue-content\">");
      out.print(vFaulty);
      out.write("</td> </tr>\n");
      out.write("	</table>\n");
      out.write("</td>\n");
      out.write("\n");
      out.write("<!--<td>\n");
      out.write("	<OBJECT classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\" codebase=http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0\" width=\"200\" height=\"375\" id=\"Column3D\" >\n");
      out.write("	<param name=\"movie\" value=\"../../../FusionCharts/Charts/FCF_Pie3D.swf\" />\n");
      out.write("	<param name=\"FlashVars\" value=\"&dataURL=Data.xml&chartWidth=200&chartHeight=250\">\n");
      out.write("	<param name=\"quality\" value=\"high\" />\n");
      out.write("	<embed src=\"../../../FusionCharts/Charts/FCF_Pie3D.swf\" flashVars=\"&dataXML=");
      out.print(strXML1);
      out.write("&chartWidth=250&chartHeight=200\" quality=\"high\" width=\"250\" height=\"250\" name=\"stats\" type=\"application/x-shockwave-flash\" pluginspage=\"http://www.macromedia.com/go/getflashplayer\" />\n");
      out.write("	</object>\n");
      out.write("	<table border=\"1\" cellpadding=\"1\" cellspacing=\"1\" class=\"border\">\n");
      out.write("	<tr><td><a href=\"stnlist1.jsp?v1=t\" target=\"_blank\" class=\"Blue-content\">Total</td><td class=\"content style1\"><a href=\"stnlist1.jsp?v1=t\" target=\"_blank\" class=\"Blue-content\">");
      out.print(vTotal1);
      out.write("</td> </tr>\n");
      out.write("	<tr><td><a href=\"stnlist1.jsp?v1=w\" target=\"_blank\" class=\"Blue-content\">Working</td><td class=\"content style1\"><a href=\"stnlist1.jsp?v1=w\" target=\"_blank\" class=\"Blue-content\">");
      out.print(vWorking1);
      out.write("</td> </tr>\n");
      out.write("	<tr><td><a href=\"stnlist1.jsp?v1=n\" target=\"_blank\" class=\"Blue-content\">Not Working</td><td class=\"content style1\"><a href=\"stnlist1.jsp?v1=n\" target=\"_blank\" class=\"Blue-content\">");
      out.print(vFaulty1);
      out.write("</td> </tr>\n");
      out.write("	</table>\n");
      out.write("</td>-->\n");
      out.write("<!--<td><iframe src=\"stationstatsper.jsp\" height=\"300\"  width=\"300\" FRAMEBORDER=\"0\"  scrolling=\"No\"></iframe></td> -->\n");
      out.write("<td><iframe src=\"stationstatsperbar.jsp\" height=\"300\"  width=\"300\" FRAMEBORDER=\"0\"  scrolling=\"No\"></iframe></td> \n");
      out.write("<!--<td><iframe src=\"stationstatsperbar1.jsp\" height=\"300\"  width=\"300\" FRAMEBORDER=\"0\"  scrolling=\"No\"></iframe></td>-->\n");
      out.write("\n");
      out.write("<!--<td><iframe src=\"messagestats.jsp\" height=\"300\" width=\"300\" FRAMEBORDER=\"0\" scrolling=\"No\"></iframe></td>\n");
      out.write(" <td><iframe src=\"recoverystats.jsp\" height=\"300\"  width=\"250\" FRAMEBORDER=\"0\" scrolling=\"No\"></iframe></td> \n");
      out.write("<td><iframe src=\"alerts.jsp\" height=\"300\" width=\"600\" FRAMEBORDER=\"0\" scrolling=\"Yes \"></iframe></td>-->\n");
      out.write("\n");
      out.write("\n");
      out.write("</tr>\n");
      out.write("</table>\n");

stmt.close();
rs.close();

      out.write("\n");
      out.write("</BODY>\n");
      out.write("</HTML>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
