/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.91
 * Generated at: 2024-10-15 11:41:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.reports;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import com.ConnectionProvider;
import java.text.*;

public final class rainview_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


Connection con=null;
ResultSet rs=null;
Statement stmt=null;
Statement stmt2=null;
String query="";
String e; 
String vdist="";
int count;

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(7);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.text");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.ConnectionProvider");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write(" \n");
      out.write("\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("\n");
      out.write("\n");
      out.write("function parameter(){\n");
      out.write("var vid1 = document.getElementById(\"state\").value\n");
      out.write("		if (vid1==null || vid1==\"\"){vid1=0;}\n");
      out.write("var vid2 = document.getElementById(\"district\").value\n");
      out.write("		if (vid2==null || vid2==\"\"){vid2=0;}\n");
      out.write("var vid3 = 0\n");
      out.write("var vid4 = 0\n");
      out.write("var vfdate= document.getElementById(\"fdate\").value\n");
      out.write("var vfhr= document.getElementById(\"fhr\").value	\n");
      out.write("var vfmin= document.getElementById(\"fmin\").value\n");
      out.write("window.location.replace(\"rainview.jsp?value1=\"+vid1+\"&&value2=\"+vid2+\"&&value3=\"+vid3+\"&&value4=\"+vid4+\"&&vfdate=\"+vfdate+\"&&fhr=\"+vfhr+\"&&fmin=\"+vfmin);\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write('\n');

String value1=request.getParameter("value1");
String value2=request.getParameter("value2");
String value3=request.getParameter("value3");
String value4=request.getParameter("value4");
String vfhr=request.getParameter("fhr");
String vfmin=request.getParameter("fmin");

if (value1==null){value1="0";}
if (value2==null){value2="0";}
if (value3==null){value3="0";}
if (value4==null){value4="0";}

String vfdate=request.getParameter("vfdate");
String vtdate=request.getParameter("vtdate");

DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
String formattedDate = df.format(new java.util.Date());

if(vfdate == null){ 
 vfdate=formattedDate;
// vtdate=formattedDate;
 vfhr="00";
 vfmin="00";
}

con = ConnectionProvider.getCon();
stmt=con.createStatement();
stmt2=con.createStatement();
rs = stmt.executeQuery("select param_id as sid,group_value as state from parameter where active='Y' and group_family='LOCATION' and Group_name='STATE'");

      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<link href=\"../../styles/text.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("<script type=\"text/javascript\" src=\"../../Script/datepicker.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<table width=\"100%\" border=\"1\" cellpadding=\"1\"  bgcolor=\"#DBEBFF\" VALIGN=TOP>\n");
      out.write("<tr><td width=\"10%\" VALIGN=TOP>\n");
      out.write("<table width=\"10%\" border=\"1\" cellpadding=\"1\"  bgcolor=\"#DBEBFF\" VALIGN=TOP>\n");
      out.write("<!--   date selection starts here -->\n");
      out.write("\n");
      out.write("<tr><td class=\"Blue-content\" colspan=\"4\"><b>Select Date Range</b></td></tr>\n");
      out.write("<tr><td class=\"content style1\" align=\"right\"><b>From</b></td>\n");
      out.write("<td><input id=\"fdate\"  class=\"content style1\" type=\"text\" name=\"fdate\" size=\"10\" maxlength=\"10\" value=");
      out.print(vfdate);
      out.write(">\n");
      out.write("<a href=\"javascript:NewCal('fdate','ddmmyyyy',false)\"><img src=\"../../images/calendar.JPG\" width=\"16\" height=\"16\" border=\"0\" alt=\"Pick a date\"></a>\n");
      out.write("<select id=\"fhr\" class=\"content style1\">\n");
 for (int i=0; i<24; i++) {
	e=Integer.toString(i);
	if (e.length()==1){e="0"+e;}
      out.write("\n");
      out.write("<option value=\"");
      out.print(e);
      out.write('"');
      out.write('>');
      out.print(e);
      out.write("</option>\n");
}
      out.write("\n");
      out.write("<option value=");
      out.print(vfhr);
      out.write(" selected disabled>");
      out.print(vfhr);
      out.write("</option>\n");
      out.write("</select><a class=\"content style1\">Hr</a>\n");
      out.write("<select id=\"fmin\" class=\"content style1\">\n");
 	for (int i=0; i<60; i++) {
		e=Integer.toString(i);
		if (e.length()==1){e="0"+e;}
      out.write("\n");
      out.write("<option value=\"");
      out.print(e);
      out.write('"');
      out.write('>');
      out.print(e);
      out.write("</option>\n");
}
      out.write("\n");
      out.write("<option value=");
      out.print(vfmin);
      out.write(" selected disabled>");
      out.print(vfmin);
      out.write("</option>\n");
      out.write("</select><a class=\"content style1\">Mi</a>\n");
      out.write("</td></tr>\n");
      out.write("\n");
      out.write("\n");
      out.write(" <!-- date selection Ends here -->\n");
      out.write("<tr><td class=\"Blue-content\" colspan=\"6\" align=\"left\">Select Station</td></tr>\n");
      out.write("<tr><td class=\"content style1\"><b> State </b></td>\n");
      out.write("<td>\n");
      out.write("<select id=\"state\" onchange=\"parameter()\" class=\"content style1\">\n");
      out.write("<option value=\"0\">--Please Select--</option>\n");
 while(rs.next()){ 
      out.write("\n");
      out.write("<option value=\"");
      out.print(rs.getInt("sid"));
      out.write('"');
      out.write('>');
      out.print(rs.getString("state"));
      out.write("</option>\n");
      out.write("\n");
 if(rs.getString("sid").equals(value1)){
      out.write("\n");
      out.write("<option value=\"");
      out.print(value1);
      out.write("\" selected disabled>");
      out.print(rs.getString("state"));
      out.write("</option> \n");

}

}

      out.write("\n");
      out.write("</select> </td></tr>\n");
      out.write("<tr><td class=\"content style1\"><b> District</b> </td><td>\n");
      out.write("<select id=\"district\" onchange=\"parameter()\" class=\"content style1\">\n");
      out.write("<option value=\"0\">--Please Select--</option>\n");
      out.write("<option value=\"-1\">All</option>\n");

rs=stmt.executeQuery("select param_id as did,group_value as district from parameter where active='Y' and group_family='LOCATION' and Group_name='DISTRICT' and parent_group='"+value1+"'  order by 2");

while(rs.next()){

      out.write("\n");
      out.write("<option value=\"");
      out.print(rs.getInt("did"));
      out.write('"');
      out.write(' ');
      out.write('>');
      out.print(rs.getString("district"));
      out.write("</option>\n");
 if(rs.getString("did").equals(value2)){
      out.write("\n");
      out.write("<option value=\"");
      out.print(value2);
      out.write("\" selected disabled>");
      out.print(rs.getString("district"));
      out.write("</option>\n");

		//updating the Audit_table
		count=stmt2.executeUpdate("insert into audit_table values((select user_id from users where user_role="+session.getAttribute("theRole")+" and login_name='"+session.getAttribute("theName")+"'),(select user_role from users where user_role="+session.getAttribute("theRole")+" and login_name='"+session.getAttribute("theName")+"'),'Rainfall at Specific Time','now()')");
  //end of auditing
}
}

      out.write("\n");
      out.write("</select>\n");
      out.write("</td></tr>\n");
      out.write("\n");
      out.write("</table>\n");
      out.write("</td>\n");
      out.write("<td valign=top>\n");
      out.write("<table width=\"100%\" border=\"1\" cellpadding=\"0\" cellspacing=\"0\" id=\"stretch\" >\n");
      out.write("	<tr><td class=\"Headings\" align=\"center\">Rainfall at Specific Time Report</td></tr>\n");
      out.write("	\n");
      out.write("	");
 
	if (!"0".equalsIgnoreCase(value2)||"-1".equalsIgnoreCase(value2)){
	query="select group_value as district from parameter where param_id='"+value2+"'";
	rs=stmt.executeQuery(query);
	while(rs.next()){ vdist="for "+rs.getString(1)+" District at";}
	if ("-1".equalsIgnoreCase(value2)){vdist=" for All Districts at";}
	if (!"".equalsIgnoreCase(vdist)){ 
      out.write("\n");
      out.write("	<tr><td class=\"Red-content\" align=\"center\">");
      out.print(vdist+" "+vfdate+" "+vfhr+":"+vfmin );
      out.write("</td></tr>\n");
      out.write("	");
}
	}
      out.write("\n");
      out.write("	<tr><td>\n");
      out.write("	<table width=\"100%\" border=\"1\" cellpadding=\"0\" cellspacing=\"0\" id=\"stretch\" > \n");
      out.write("	<tr class=\"Blue-content\" align=\"center\">\n");
      out.write("<td>Sl.</td>\n");
      out.write("<td>ClientID</td>\n");
      out.write("<td>District</td>\n");
      out.write("<td>Mandal</td>\n");
      out.write("<td>Location</td>\n");
      out.write("<td>Latitude</td>\n");
      out.write("<td>Longitude</td>\n");
      out.write("<td>Last Updated<br>before <br>Selected Date/time<br>(24hrs)</td>\n");
      out.write("<td>Rain (mm)</td>\n");
      out.write("</tr>\n");
      out.write("\n");
      out.write("\n");
 if(value1.equalsIgnoreCase("0") & value2.equalsIgnoreCase("0")){
      out.write("\n");
      out.write("<tr><td colspan=7 class=\"readonly\" align=\"center\">Select Date and Location</td><tr>\n");
}
else if (!value1.equalsIgnoreCase("0") & !value2.equalsIgnoreCase("0")){

query="select x.clientid,(select group_value from parameter where param_id=district) as district,coalesce((select group_value from parameter where param_id=county),'-') as county,x.location,latitude,longitude,coalesce(y.packet_date,'N/A') as packet_date, y.rain from station_configs_det as x left outer join ";
query=query+" (select a.clientid,to_char(a.packet_date,'mm/dd/yyyy hh24:mi') as packet_date,rain from data_packets a, (select clientid,max(packet_date) as packet_date from data_packets where rain is not null and packet_date between ";
query=query+" to_timestamp('"+vfdate+","+vfhr+":"+vfmin+"','dd/mm/yyyy,hh24:mi') - INTERVAL '24 hours' and  to_timestamp('"+vfdate+","+vfhr+":"+vfmin+"','dd/mm/yyyy,hh24:mi')+INTERVAL '1 SEC' and packet_type='D' group by clientid ) as b where  a.clientid=b.clientid and a.packet_date=b.packet_date and  packet_type='D'  ) as y on (x.clientid=y.clientid) ";


if(value2.equalsIgnoreCase("0")||value2.equalsIgnoreCase("-1"))
{
	query=query+" where state="+value1;
			//updating the Audit_table
		count=stmt2.executeUpdate("insert into audit_table values((select user_id from users where user_role="+session.getAttribute("theRole")+" and login_name='"+session.getAttribute("theName")+"'),(select user_role from users where user_role="+session.getAttribute("theRole")+" and login_name='"+session.getAttribute("theName")+"'),'Rainfall at Specific Time','now()')");
  //end of auditing
}
else{
	query=query+" where district='"+value2+"'";
					}
query=query+" order by district,county,location";
//out.println(query);
rs=stmt.executeQuery(query);
	int i=0;
while(rs.next()){
i=i+1;

      out.write("\n");
      out.write("<tr align =\"left\" class=\"readonly\">\n");
      out.write("<td>");
      out.print(i);
      out.write("</td>\n");
      out.write("<td>");
      out.print(rs.getString("clientid"));
      out.write("</td>\n");
      out.write("<td>");
      out.print(rs.getString("district"));
      out.write("</td>\n");
      out.write("<td>");
      out.print(rs.getString("county"));
      out.write("</td>\n");
      out.write("<td>");
      out.print(rs.getString("location"));
      out.write("</td>\n");
      out.write("<td>");
      out.print(rs.getString("latitude"));
      out.write("</td>\n");
      out.write("<td>");
      out.print(rs.getString("longitude"));
      out.write("</td>\n");
      out.write("<td>");
      out.print(rs.getString("packet_date"));
      out.write("</td>\n");
 if (rs.getString("rain")==null){ 
      out.write("<td align=\"right\">N/A</td>");
} else {
      out.write("<td align=\"right\">");
      out.print(rs.getDouble("rain"));
      out.write("</td>");
}
      out.write("\n");
      out.write("\n");
      out.write("</tr>\n");

}
}

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</table>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("	</table>\n");
      out.write("</td></tr>\n");
      out.write("</table>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
