/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.91
 * Generated at: 2024-10-15 11:39:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.reports;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.ConnectionProvider;
import java.io.*;
import java.sql.*;
import java.text.*;

public final class reportpercent_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


Connection con=null;
ResultSet rs=null;
Statement stmt=null;
Statement stmt2=null;
String query="";
String e; 
int count;

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(8);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.text");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.ConnectionProvider");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write(" \n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("\n");
      out.write("function params(){\n");
      out.write("var vid1 = document.getElementById(\"state\").value\n");
      out.write("var vid2 =document.getElementById(\"district\").value\n");
      out.write("var vfdate= document.getElementById(\"fdate\").value\n");
      out.write("var vtdate= document.getElementById(\"tdate\").value\n");
      out.write("var vparam= document.getElementById(\"param\").value\n");
      out.write("	var vfhr= document.getElementById(\"fhr\").value	\n");
      out.write("	var vfmin= document.getElementById(\"fmin\").value\n");
      out.write("	var vthr= document.getElementById(\"thr\").value\n");
      out.write("	var vtmin= document.getElementById(\"tmin\").value\n");
      out.write("window.location.replace(\"reportpercent.jsp?value1=\"+vid1+\"&&value2=\"+vid2+\"&&vfdate=\"+vfdate+\"&&vtdate=\"+vtdate+\"&&fhr=\"+vfhr+\"&&fmin=\"+vfmin+\"&&thr=\"+vthr+\"&&tmin=\"+vtmin+\"&&param=\"+vparam);\n");
      out.write("}\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("\n");
      out.write('\n');

String value1=request.getParameter("value1");
String value2=request.getParameter("value2");
String vfdate=request.getParameter("vfdate");
String vtdate=request.getParameter("vtdate");
String vparam=request.getParameter("param");
	String vfhr=request.getParameter("fhr");
	String vfmin=request.getParameter("fmin");
	String vthr=request.getParameter("thr");
	String vtmin=request.getParameter("tmin");

if (value1==null){value1="0";}
if (value2==null){value2="0";}
if (vparam==null) {vparam="All";}


DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
String formattedDate = df.format(new java.util.Date());


if(vfdate == null){ 
 vfdate=formattedDate;
 vtdate=formattedDate;
 vfhr="00";
 vfmin="00";
 vthr="00";
 vtmin="00";
}

con = ConnectionProvider.getCon();
stmt=con.createStatement();
stmt2=con.createStatement();
rs = stmt.executeQuery("select param_id as sid,group_value as state from parameter where active='Y' and group_family='LOCATION' and Group_name='STATE'");

      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<link href=\"../../styles/text.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("<script type=\"text/javascript\" src=\"../../Script/datepicker.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<table width=\"100%\" border=\"1\" cellpadding=\"1\"  bgcolor=\"#DBEBFF\" VALIGN=TOP>\n");
      out.write("<tr><td width=\"10%\" VALIGN=TOP>\n");
      out.write("<table width=\"10%\" border=\"1\" cellpadding=\"1\"  bgcolor=\"#DBEBFF\" VALIGN=TOP>\n");
      out.write("\n");
      out.write("<!--   date selection starts here -->\n");
      out.write("\n");
      out.write("<tr><td class=\"Blue-content\" colspan=\"4\"><b>Select Date Range</b></td></tr>\n");
      out.write("<tr><td class=\"content style1\" align=\"right\"><b>From</b></td>\n");
      out.write("<td>\n");
      out.write(" <input id=\"fdate\"  class=\"content style1\" type=\"text\" name=\"fdate\" size=\"10\" maxlength=\"12\" value=");
      out.print(vfdate);
      out.write(">\n");
      out.write("<a href=\"javascript:NewCal('fdate','ddmmyyyy',false)\"><img src=\"../../images/calendar.JPG\" width=\"16\" height=\"16\" border=\"0\" alt=\"Pick a date\"></a>\n");
      out.write("<select id=\"fhr\" class=\"content style1\">\n");
 for (int i=0; i<24; i++) {
	e=Integer.toString(i);
	if (e.length()==1){e="0"+e;}
      out.write("\n");
      out.write("<option value=\"");
      out.print(e);
      out.write('"');
      out.write('>');
      out.print(e);
      out.write("</option>\n");
}
      out.write("\n");
      out.write("<option value=");
      out.print(vfhr);
      out.write(" selected disabled>");
      out.print(vfhr);
      out.write("</option>\n");
      out.write("</select><a class=\"content style1\">Hr</a>\n");
      out.write("<select id=\"fmin\" class=\"content style1\">\n");
 	for (int i=0; i<60; i++) {
		e=Integer.toString(i);
		if (e.length()==1){e="0"+e;}
      out.write("\n");
      out.write("<option value=\"");
      out.print(e);
      out.write('"');
      out.write('>');
      out.print(e);
      out.write("</option>\n");
}
      out.write("\n");
      out.write("<option value=");
      out.print(vfmin);
      out.write(" selected disabled>");
      out.print(vfmin);
      out.write("</option>\n");
      out.write("</select><a class=\"content style1\">Mi</a>\n");
      out.write("</td>\n");
      out.write("\n");
      out.write("</td>\n");
      out.write("</tr>\n");
      out.write("<tr><td class=\"content style1\" align=\"right\"><b>To</b></td>\n");
      out.write("<td><input id=\"tdate\"  class=\"content style1\" type=\"text\" name=\"tdate\" size=\"10\" maxlength=\"12\" value=");
      out.print(vtdate);
      out.write(">\n");
      out.write("<a href=\"javascript:NewCal('tdate','ddmmyyyy',false)\"><img src=\"../../images/calendar.JPG\" width=\"16\" height=\"16\" border=\"0\" alt=\"Pick a date\"></a>\n");
      out.write("<select id=\"thr\" class=\"content style1\">\n");
 for (int i=0; i<24; i++) {
	e=Integer.toString(i);
	if (e.length()==1){e="0"+e;}
      out.write("\n");
      out.write("<option value=\"");
      out.print(e);
      out.write('"');
      out.write('>');
      out.print(e);
      out.write("</option>\n");
}
      out.write("\n");
      out.write("<option value=");
      out.print(vthr);
      out.write(" selected disabled>");
      out.print(vthr);
      out.write("</option>\n");
      out.write("</select><a class=\"content style1\">Hr</a>\n");
      out.write("<select id=\"tmin\" class=\"content style1\">\n");
 	for (int i=0; i<60; i++) {
		e=Integer.toString(i);
		if (e.length()==1){e="0"+e;}
      out.write("\n");
      out.write("<option value=\"");
      out.print(e);
      out.write('"');
      out.write('>');
      out.print(e);
      out.write("</option>\n");
}
      out.write("\n");
      out.write("<option value=");
      out.print(vtmin);
      out.write(" selected disabled>");
      out.print(vtmin);
      out.write("</option>\n");
      out.write("</select><a class=\"content style1\">Mi</a>\n");
      out.write("</td>\n");
      out.write("</tr>\n");
      out.write("\n");
      out.write(" <!-- date selection Ends here -->\n");
      out.write("\n");
      out.write("<!--percentage selection -->\n");
      out.write("<tr><td class=\"Blue-content\" colspan=\"6\" align=\"left\">Reported\n");
      out.write("<select id=\"param\" onchange=\"params()\" class=\"content style1\">\n");
      out.write("<option value=\"All\">All</option>\n");
      out.write("<option value=\"90\">90</option>\n");
      out.write("<option value=\"80\">80</option>\n");
      out.write("<option value=\"70\">70</option>\n");
      out.write("<option value=\"60\">60</option>\n");
      out.write("<option value=\"50\">50</option>\n");
      out.write("<option value=\"50Lower\">50Lower</option>\n");
      out.write("<option value=\"NotReporting\">NotReporting</option>\n");
      out.write("<option value=");
      out.print(vparam);
      out.write(" selected disabled>");
      out.print(vparam);
      out.write("</option> \n");
      out.write("</select>% </td></tr>\n");
      out.write("\n");
      out.write("<!--sensor selection -->\n");
      out.write("\n");
      out.write("<tr><td class=\"Blue-content\" colspan=\"6\" align=\"left\">Select Station</td></tr>\n");
      out.write("<tr><td class=\"content style1\"><b> State </b></td>\n");
      out.write("<td>\n");
      out.write("<select id=\"state\" onchange=\"params()\" class=\"content style1\">\n");
      out.write("<option value=\"0\">--Please Select--</option>\n");
 while(rs.next()){ 
      out.write("\n");
      out.write("<option value=\"");
      out.print(rs.getInt("sid"));
      out.write('"');
      out.write('>');
      out.print(rs.getString("state"));
      out.write("</option>\n");
      out.write("\n");
 if(rs.getString("sid").equals(value1)){
      out.write("\n");
      out.write("<option value=\"");
      out.print(value1);
      out.write("\" selected disabled>");
      out.print(rs.getString("state"));
      out.write("</option> \n");

}

}

      out.write("\n");
      out.write("</select> </td></tr>\n");
      out.write("<tr><td class=\"content style1\"><b> District</b> </td><td>\n");
      out.write("<select id=\"district\" onchange=\"params()\" class=\"content style1\">\n");
      out.write("<option value=\"0\">--Please Select--</option>\n");
      out.write("<option value=\"-1\">All</option>\n");
      out.write("\n");

rs=stmt.executeQuery("select param_id as did,group_value as district from parameter where active='Y' and group_family='LOCATION' and Group_name='DISTRICT' and parent_group='"+value1+"' order by group_value");

while(rs.next()){

      out.write("\n");
      out.write("<option value=\"");
      out.print(rs.getInt("did"));
      out.write('"');
      out.write(' ');
      out.write('>');
      out.print(rs.getString("district"));
      out.write("</option>\n");
 if(rs.getString("did").equals(value2)){
      out.write("\n");
      out.write("<option value=\"");
      out.print(value2);
      out.write("\" selected disabled>");
      out.print(rs.getString("district"));
      out.write("</option>\n");

	//updating the Audit_table
		count=stmt2.executeUpdate("insert into audit_table values((select user_id from users where user_role="+session.getAttribute("theRole")+" and login_name='"+session.getAttribute("theName")+"'),(select user_role from users where user_role="+session.getAttribute("theRole")+" and login_name='"+session.getAttribute("theName")+"'),'Report By Percentage','now()')");
  //end of auditing
}
}

      out.write("\n");
      out.write("</select>\n");
      out.write("</td></tr>\n");
      out.write("</table>\n");
      out.write("</td>\n");
      out.write("<td valign=top>\n");
      out.write("\n");
      out.write("<table width=\"100%\" border=\"0\" cacellpadding=\"0\" cellspacing=\"0\" id=\"stretch\" > \n");
      out.write("	<tr><td class=\"Headings\" align=\"center\" width=\"80%\">Reporting Stations (Percentage)</td></tr>\n");
      out.write("	<tr><td><br></td></tr>\n");
      out.write("	<tr><td class=\"Blue-content\" align=\"center\" width=\"80%\">from ");
      out.print(vfdate);
      out.write(' ');
      out.print(vfhr);
      out.write(':');
      out.print(vfmin);
      out.write(" Hrs to ");
      out.print(vtdate);
      out.write(' ');
      out.print(vthr);
      out.write(':');
      out.print(vtmin);
      out.write(" Hrs</td></tr>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<tr><td colspan=2><table width=\"100%\" border=\"1\" cellpadding=\"0\" cellspacing=\"0\" id=\"stretch\" > \n");
      out.write("\n");
      out.write("<tr class=\"Blue-content\">\n");
      out.write("<td>Client Id</td><td>District</td><td>Mandal</td><td>Location</td><td>Latitude</td><td>Longitude</td>\n");
      out.write("<td>Messages<BR>Received</td>\n");
      out.write("</tr>\n");
      out.write("\n");


//out.println(vparam);
query="select * from (select a.clientid,latitude,longitude,location,(select group_value from parameter where param_id=state) as state,(select group_value from parameter where param_id=district) as district,coalesce((select group_value from parameter where param_id=county),'-') as county , received/(date_part('epoch',((to_timestamp('"+vtdate+","+vthr+":"+vtmin+"','dd/mm/yyyy,hh24:mi')  -to_timestamp('"+vfdate+","+vfhr+":"+vfmin+"','dd/mm/yyyy,hh24:mi') ) ::interval)/60)/datafreq)*100 as received_per from station_configs_det as a left outer join (";

query=query+" select clientid,count(1) as received from data_packets where packet_type='D' and  packet_date >= to_timestamp('"+vfdate+","+vfhr+":"+vfmin+"','dd/mm/yyyy,hh24:mi') and packet_date < to_timestamp('"+vtdate+","+vthr+":"+vtmin+"','dd/mm/yyyy,hh24:mi') and packet_type='D' group by clientid) as b on (a.clientid=b.clientid) where 1=1 ";


if(value2.equalsIgnoreCase("-1")) {	query=query+" and state='"+value1+"') as X ";
	//updating the Audit_table
		count=stmt2.executeUpdate("insert into audit_table values((select user_id from users where user_role="+session.getAttribute("theRole")+" and login_name='"+session.getAttribute("theName")+"'),(select user_role from users where user_role="+session.getAttribute("theRole")+" and login_name='"+session.getAttribute("theName")+"'),'Report By Percentage','now()')");
  //end of auditing
  }
else{ query=query+" and district='"+value2+"') as X ";}

if(vparam.equalsIgnoreCase("50Lower")) {query=query+" where received_per< 50";}
if(vparam.equalsIgnoreCase("NotReporting")) {query=query+" where (received_per=0 or received_per is null)";}

query=query+" order by state,district,county,location";
//out.println(query);

rs=stmt.executeQuery(query);

	while(rs.next()){

      out.write("\n");
      out.write("<tr  class=\"readonly\">\n");
      out.write("<td>");
      out.print(rs.getString("clientid"));
      out.write("</td><td>");
      out.print(rs.getString("district"));
      out.write("</td><td>");
      out.print(rs.getString("county"));
      out.write("</td>\n");
      out.write("<td>");
      out.print(rs.getString("location"));
      out.write("</td><td>");
      out.print(rs.getString("latitude"));
      out.write("</td><td>");
      out.print(rs.getString("longitude"));
      out.write("</td>\n");
      out.write("<td>");
      out.print(rs.getInt("received_per"));
      out.write("%</td>\n");
      out.write("</tr>\n");
} 
      out.write("\n");
      out.write("</tr></table>\n");
      out.write("\n");
      out.write("</table>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("	</table>\n");
      out.write("</td></tr>\n");
      out.write("</table>\n");

rs.close();

      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
