/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.91
 * Generated at: 2024-10-17 06:58:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.reports;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import com.ConnectionProvider;

public final class lastreported_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


Connection con=null;
ResultSet rs=null;
Statement stmt=null;
Statement stmt2=null;
String query="";
int count;

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.ConnectionProvider");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write(" \n");
      out.write("\n");
      out.write("<script>\n");
      out.write("\n");
      out.write("function params(){\n");
      out.write("var vid1 = document.getElementById(\"state\").value\n");
      out.write("var vid2 =document.getElementById(\"district\").value\n");
      out.write("window.location.replace(\"/wms/jsp/reports/lastreported.jsp?value1=\"+vid1+\"&&value2=\"+vid2);\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("\n");
      out.write('\n');

String value1=request.getParameter("value1");
String value2=request.getParameter("value2");
if (value1==null){value1="0";}
if (value2==null){value2="0";}

con = ConnectionProvider.getCon();
stmt=con.createStatement();
stmt2=con.createStatement();
rs = stmt.executeQuery("select param_id as sid,group_value as state from parameter where active='Y' and group_family='LOCATION' and Group_name='STATE'");

      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<link href=\"../../styles/text.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<table width=\"100%\" border=\"1\" cellpadding=\"1\"  bgcolor=\"#DBEBFF\" VALIGN=TOP>\n");
      out.write("<tr><td width=\"10%\" VALIGN=TOP>\n");
      out.write("<table width=\"10%\" border=\"1\" cellpadding=\"1\"  bgcolor=\"#DBEBFF\" VALIGN=TOP>\n");
      out.write("\n");
      out.write("<tr><td class=\"Blue-content\" colspan=\"6\" align=\"left\">Select Station</td></tr>\n");
      out.write("<tr><td class=\"content style1\"><b> State </b></td>\n");
      out.write("<td>\n");
      out.write("<select id=\"state\" onchange=\"params()\" class=\"content style1\">\n");
      out.write("<option value=\"0\">--Please Select--</option>\n");
 while(rs.next()){ 
      out.write("\n");
      out.write("<option value=\"");
      out.print(rs.getInt("sid"));
      out.write('"');
      out.write('>');
      out.print(rs.getString("state"));
      out.write("</option>\n");
      out.write("\n");
 if(rs.getString("sid").equals(value1)){
      out.write("\n");
      out.write("<option value=\"");
      out.print(value1);
      out.write("\" selected disabled>");
      out.print(rs.getString("state"));
      out.write("</option> \n");

}

}

      out.write("\n");
      out.write("</select> </td></tr>\n");
      out.write("<tr><td class=\"content style1\"><b> District</b> </td><td>\n");
      out.write("<select id=\"district\" onchange=\"params()\" class=\"content style1\">\n");
      out.write("<option value=\"0\">--Please Select--</option>\n");
      out.write("<option value=\"-1\">All</option>\n");
      out.write("\n");

rs=stmt.executeQuery("select param_id as did,group_value as district from parameter where active='Y' and group_family='LOCATION' and Group_name='DISTRICT' and parent_group='"+value1+"' order by group_value");

while(rs.next()){

      out.write("\n");
      out.write("<option value=\"");
      out.print(rs.getInt("did"));
      out.write('"');
      out.write(' ');
      out.write('>');
      out.print(rs.getString("district"));
      out.write("</option>\n");
 if(rs.getString("did").equals(value2)){
      out.write("\n");
      out.write("<option value=\"");
      out.print(value2);
      out.write("\" selected disabled>");
      out.print(rs.getString("district"));
      out.write("</option>\n");


	//updating the Audit_table
		count=stmt2.executeUpdate("insert into audit_table values((select user_id from users where user_role="+session.getAttribute("theRole")+" and login_name='"+session.getAttribute("theName")+"'),(select user_role from users where user_role="+session.getAttribute("theRole")+" and login_name='"+session.getAttribute("theName")+"'),'Last Reported','now()')");
  //end of auditing
}
}

      out.write("\n");
      out.write("</select>\n");
      out.write("</td></tr>\n");
      out.write("</table>\n");
      out.write("</td>\n");
      out.write("<td valign=top>\n");
      out.write("\n");
      out.write("<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" id=\"stretch\" > \n");
      out.write("	<tr><td class=\"Headings\" align=\"center\">Last Reported Stations</td></tr>\n");
      out.write("	<tr><td><table width=\"100%\" border=\"1\" cellpadding=\"0\" cellspacing=\"0\" id=\"stretch\" > \n");
      out.write("<tr><td class=\"Blue-content\">Client Id</td>\n");
      out.write("<td class=\"Blue-content\">Location</td>\n");
      out.write("<td class=\"Blue-content\">Latitude</td>\n");
      out.write("<td class=\"Blue-content\">Longitude</td>\n");
      out.write("<!-- <td class=\"Blue-content\">State</td> -->\n");
      out.write("<td class=\"Blue-content\">District</td>\n");
      out.write("<td class=\"Blue-content\">Packet DateTime</td>\n");
      out.write("<td class=\"Blue-content\">Rain Packet</td>\n");
      out.write("<td class=\"Blue-content\">Temp Packet</td>\n");
      out.write("<td class=\"Blue-content\">Humidity Packet</td>\n");
      out.write("<td class=\"Blue-content\">WindSpeed Packet</td>\n");
      out.write("<td class=\"Blue-content\">WindDirection Packet</td>\n");
      out.write("<td class=\"Blue-content\">Pressure Packet</td>\n");
      out.write("</tr>\n");

	
query="select clientid,location,state,district,longitude,latitude,coalesce(to_char(last_packet,'mm/dd/yyyy hh24:mi'),null,'-') as last_packet, coalesce(to_char(rain_sensors,'mm/dd/yyyy hh24:mi'),null,'-') as rain_sensors, coalesce(to_char(temp_sensors,'mm/dd/yyyy hh24:mi'),null,'-') as temp_sensors, coalesce(to_char(humid_sensors,'mm/dd/yyyy hh24:mi'),null,'-') as humid_sensors, coalesce(to_char(wind_sensors,'mm/dd/yyyy hh24:mi'),null,'-') as wind_sensors, coalesce(to_char(winddir_sensors,'mm/dd/yyyy hh24:mi'),null,'-') as winddir_sensors, coalesce(to_char(pressure_sensors,'mm/dd/yyyy hh24:mi'),null,'-') as pressure_sensors from ( select st.clientid,latitude,longitude,location,(select group_value from parameter where param_id=state) as state,(select group_value from parameter where param_id=district) as district,county,last_packet,rain_sensors,temp_sensors,humid_sensors,wind_sensors,winddir_sensors,pressure_sensors from station_configs_det as st left outer join  ( select clientid,max(packet_date) as last_packet, max(case when rain is not null then packet_date end) as rain_sensors, max(case when temp is not null then packet_date end) as temp_sensors,max(case when humidity is not null then packet_date end) as humid_sensors, max(case when wind is not null then packet_date end) as wind_sensors, max(case when wind_direction is not null then packet_date end) as winddir_sensors,  max(case when local_pressure is not null then packet_date end) as pressure_sensors from data_packets  group by clientid ) as dp on st.clientid=dp.clientid where st.activate!=0";

if(value2.equalsIgnoreCase("-1"))
{
	query=query+" and state="+value1+") as x";
	//updating the Audit_table
		count=stmt2.executeUpdate("insert into audit_table values((select user_id from users where user_role="+session.getAttribute("theRole")+" and login_name='"+session.getAttribute("theName")+"'),(select user_role from users where user_role="+session.getAttribute("theRole")+" and login_name='"+session.getAttribute("theName")+"'),'Last Reported','now()')");
  //end of auditing
}
else{
	query=query+" and district='"+value2+"') as x";
					}
rs=stmt.executeQuery(query);


System.out.println(query);
	rs=stmt.executeQuery(query);
	while(rs.next()){

      out.write("\n");
      out.write("<tr><td class=\"readonly\">");
      out.print(rs.getString("clientid"));
      out.write("</td>\n");
      out.write("<td class=\"readonly\">");
      out.print(rs.getString("location"));
      out.write("</td>\n");
      out.write("<td class=\"readonly\">");
      out.print(rs.getString("latitude"));
      out.write("</td>\n");
      out.write("<td class=\"readonly\">");
      out.print(rs.getString("longitude"));
      out.write("</td>\n");
      out.write("<!-- <td class=\"readonly\">");
      out.print(rs.getString("state"));
      out.write("</td> -->\n");
      out.write("<td class=\"readonly\">");
      out.print(rs.getString("district"));
      out.write("</td>\n");
      out.write("<td class=\"readonly\">");
      out.print(rs.getString("last_packet"));
      out.write("</td>\n");
      out.write("<td class=\"readonly\">");
      out.print(rs.getString("rain_sensors"));
      out.write("</td>\n");
      out.write("<td class=\"readonly\">");
      out.print(rs.getString("temp_sensors"));
      out.write("</td>\n");
      out.write("<td class=\"readonly\">");
      out.print(rs.getString("humid_sensors"));
      out.write("</td>\n");
      out.write("<td class=\"readonly\">");
      out.print(rs.getString("wind_sensors"));
      out.write("</td>\n");
      out.write("<td class=\"readonly\">");
      out.print(rs.getString("winddir_sensors"));
      out.write("</td>\n");
      out.write("<td class=\"readonly\">");
      out.print(rs.getString("pressure_sensors"));
      out.write("</td>\n");
      out.write("</tr>\n");

}

      out.write("\n");
      out.write("\n");
      out.write("</tr></table>\n");
      out.write("\n");
      out.write("</table>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("	</table>\n");
      out.write("</td></tr>\n");
      out.write("</table>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
