/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.91
 * Generated at: 2024-10-08 10:55:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.ConnectionProvider;
import java.io.*;
import java.sql.*;
import java.text.*;

public final class recovery_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


Connection con=null;
ResultSet rs=null;
ResultSet rs1=null;
Statement stmt=null;
Statement stmt2=null;
String query="";
ResultSetMetaData md;
PreparedStatement pst = null;
int reccount;
int rscount;
int[] vid;

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(8);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.text");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.ConnectionProvider");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function params(){\r\n");
      out.write("var vid1 = document.getElementById(\"state\").value\r\n");
      out.write("var vid2 =document.getElementById(\"district\").value\r\n");
      out.write("var vid3 =document.getElementById(\"location\").value\r\n");
      out.write("var vfdate= document.getElementById(\"fdate\").value\r\n");
      out.write("var vtdate= document.getElementById(\"tdate\").value\r\n");
      out.write("window.location.replace(\"recovery.jsp?value1=\"+vid1+\"&&value2=\"+vid2+\"&&value3=\"+vid3+\"&&vfdate=\"+vfdate+\"&&vtdate=\"+vtdate);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function find(){\r\n");
      out.write("var vid1 = document.getElementById(\"txtFind\").value\r\n");
      out.write("alert(vid1);\r\n");
      out.write("window.location.replace(\"recovery.jsp?find=\"+vid1);\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');


String value1=request.getParameter("value1");
String value2=request.getParameter("value2");
String value3=request.getParameter("value3");
String vfdate=request.getParameter("vfdate");
String vtdate=request.getParameter("vtdate");
String act = request.getParameter("act"); 
String find=request.getParameter("find");
//out.println(find);

if (find!=null){
query="select clientid,state,district,county,location from station_configs_det where clientid='"+find+"'";	
	rs=stmt.executeQuery(query);
	while(rs.next()){
		value1=rs.getString("state");
		value2=rs.getString("district");
		value3=rs.getString("county");
	}
}


if (value1==null){value1="0";}
if (value2==null){value2="0";}
if (value3==null){value3="0";}
//if (find==null){find="0";}


DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
String formattedDate = df.format(new java.util.Date());


if(vfdate == null){ 
 vfdate=formattedDate;
 vtdate=formattedDate;
}

con = ConnectionProvider.getCon();
stmt=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
stmt2=con.createStatement();
//pst=con.prepareStatement("select packet_recovery(?)");
rs = stmt.executeQuery("select param_id as sid,group_value as state from parameter where active='Y' and group_family='LOCATION' and Group_name='STATE'");

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link href=\"../styles/text.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"../Script/datepicker.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body bgcolor=\"#DBEBFF\">\r\n");
      out.write("<form action=\"recovery.jsp\" method=\"post\" name=\"frmentry\" >\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<input type=\"hidden\" name=\"value1\" value=\"");
      out.print(value1);
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" name=\"value2\" value=\"");
      out.print(value2);
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" name=\"value3\" value=\"");
      out.print(value3);
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" name=\"vfdate\" value=\"");
      out.print(vfdate);
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" name=\"vtdate\" value=\"");
      out.print(vtdate);
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("<table width=\"100%\" border=\"0\" class=border cellpadding=\"1\"  bgcolor=\"#DBEBFF\" VALIGN=TOP id=\"stretch\"  >\r\n");
      out.write("<tr><td width=\"10%\" VALIGN=TOP>\r\n");
      out.write("<table width=\"10%\" border=\"0\" class=border cellpadding=\"1\"  bgcolor=\"#DBEBFF\" VALIGN=TOP>\r\n");
      out.write("\r\n");
      out.write("<!--   date selection starts here -->\r\n");
      out.write("\r\n");
      out.write("<tr><td class=\"Blue-content\" colspan=\"4\"><b>Select Date Range</b></td></tr>\r\n");
      out.write("<tr><td class=\"content style1\" align=\"right\"><b>From</b></td>\r\n");
      out.write("<td><input id=\"fdate\"  class=\"content style1\" type=\"text\" name=\"fdate\" size=\"10\" maxlength=\"12\" value=");
      out.print(vfdate);
      out.write(">\r\n");
      out.write("<a href=\"javascript:NewCal('fdate','ddmmyyyy',false)\"><img src=\"../images/calendar.JPG\" width=\"16\" height=\"16\" border=\"0\" alt=\"Pick a date\"></a></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr><td class=\"content style1\" align=\"right\"><b>To</b></td>\r\n");
      out.write("<td><input id=\"tdate\"  class=\"content style1\" type=\"text\" name=\"tdate\" size=\"10\" maxlength=\"12\" value=");
      out.print(vtdate);
      out.write(">\r\n");
      out.write("<a href=\"javascript:NewCal('tdate','ddmmyyyy',false)\"><img src=\"../images/calendar.JPG\" width=\"16\" height=\"16\" border=\"0\" alt=\"Pick a date\"></a></td>\r\n");
      out.write("</tr>\r\n");
      out.write(" <!-- date selection Ends here -->\r\n");
      out.write("\r\n");
      out.write("<tr><td class=\"Blue-content\" colspan=\"6\" align=\"left\">Select Station</td></tr>\r\n");
      out.write("<!-- <tr><td class=\"content style1\"><b> ID </b></td>\r\n");
      out.write("	<td><input type=text name=\"txtFind\"  class=\"content style1\" value=\"");
      out.print(find);
      out.write("\" size=\"5\">\r\n");
      out.write("	<input class=\"content style1\" type=\"submit\" value=\"Search\" onClick=\"find()\"></td></tr> -->\r\n");
      out.write("\r\n");
      out.write("<tr><td class=\"content style1\"><b> State </b></td>\r\n");
      out.write("<td>\r\n");
      out.write("<select id=\"state\" onchange=\"params()\" class=\"content style1\">\r\n");
      out.write("<option value=\"0\">--Please Select--</option>\r\n");
 while(rs.next()){ 
      out.write("\r\n");
      out.write("<option value=\"");
      out.print(rs.getInt("sid"));
      out.write('"');
      out.write('>');
      out.print(rs.getString("state"));
      out.write("</option>\r\n");
      out.write("\r\n");
 if(rs.getString("sid").equals(value1)){
      out.write("\r\n");
      out.write("<option value=\"");
      out.print(value1);
      out.write("\" selected disabled>");
      out.print(rs.getString("state"));
      out.write("</option> \r\n");

}

}

      out.write("\r\n");
      out.write("</select> </td></tr>\r\n");
      out.write("<tr><td class=\"content style1\"><b> District</b> </td><td>\r\n");
      out.write("<select id=\"district\" onchange=\"params()\" class=\"content style1\">\r\n");
      out.write("<option value=\"0\">--Please Select--</option>\r\n");
      out.write("<option value=\"-1\">All</option>\r\n");
      out.write("\r\n");

rs=stmt.executeQuery("select param_id as did,group_value as district from parameter where active='Y' and group_family='LOCATION' and Group_name='DISTRICT' and parent_group='"+value1+"' order by group_value");

while(rs.next()){

      out.write("\r\n");
      out.write("<option value=\"");
      out.print(rs.getInt("did"));
      out.write('"');
      out.write(' ');
      out.write('>');
      out.print(rs.getString("district"));
      out.write("</option>\r\n");
 if(rs.getString("did").equals(value2)){
      out.write("\r\n");
      out.write("<option value=\"");
      out.print(value2);
      out.write("\" selected disabled>");
      out.print(rs.getString("district"));
      out.write("</option>\r\n");

}
}

      out.write("\r\n");
      out.write("</select>\r\n");
      out.write("</td></tr>\r\n");
      out.write("\r\n");

query="select * from station_configs_det ";
query=query+" where state="+value1+" and district="+value2+" order by location";
rs=stmt.executeQuery(query);

      out.write("\r\n");
      out.write("<tr><td class=\"content style1\"><b> Stations</b> </td>\r\n");
      out.write("<td class=\"content style1\" align=\"left\"  >\r\n");
      out.write("<select id=\"location\" onchange=\"params()\" class=\"content style1\" size=\"20\">\r\n");
      out.write("<option value=\"0\">--Please Select--</option>\r\n");


while(rs.next()){

      out.write("\r\n");
      out.write("<option value=\"");
      out.print(rs.getInt("clientid"));
      out.write('"');
      out.write(' ');
      out.write('>');
      out.print(rs.getString("location"));
      out.write("</option>\r\n");
 if(rs.getString("clientid").equals(value3)){
      out.write("\r\n");
      out.write("<option value=\"");
      out.print(value3);
      out.write("\" selected disabled>");
      out.print(rs.getString("location"));
      out.write("</option>\r\n");

}
}

      out.write("\r\n");
      out.write("</select>\r\n");
      out.write("</td></tr>\r\n");
      out.write("<tr><td colspan=2 align=\"center\"><input type=\"submit\"  name=\"act\" value=\"Search\"><input type=\"submit\"  name=\"act\" value=\"Recover\"></td></tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("</td>\r\n");
      out.write("<td valign=top>\r\n");
      out.write("<table width=\"100%\" border=\"0\" class=border cellpadding=\"0\" cellspacing=\"0\" id=\"stretch\" > \r\n");
      out.write("	");
 	if ("Search".equalsIgnoreCase(act)&& value3!=null &&vfdate !=null && vtdate!=null ) {
		query="select check_messages("+value3+",'"+vfdate+"','"+vtdate+"')";
		//out.println(query);
		rs=stmt.executeQuery(query);
while (rs.next()){ 
      out.write("\r\n");
      out.write("	<tr class=\"readonly\" align=\"center\"><td colspan=\"6\">Found ");
      out.print(rs.getString(1));
      out.write(" missing packets </td></tr>	\r\n");
      out.write("	");
 
	}
	
	query="select id as Recover_id,clientid,to_char(fromtime,'DD/MM/YYYY HH24:MI') as Start_time,to_char(to_time,'DD/MM/YYYY HH24:MI') as End_time from packet_recovery where clientid="+value3;
		rs=stmt.executeQuery(query);
		md = rs.getMetaData();
		int count = md.getColumnCount();
		rs.last();
		rscount=rs.getRow();
		rs.beforeFirst();
		vid=new int[rscount];
		int j=0;
	
      out.write("\r\n");
      out.write("<tr class=\"Blue-content\">\r\n");

for (int i=1; i<=count; i++) {
	out.print("<td>");
	out.print((md.getColumnName(i)));
	out.print("</td>");
	}
	out.print("<td>");
//	out.print("Select");
	out.print("</td>");

out.println("</tr>");
while(rs.next()){

      out.write("\r\n");
      out.write("<tr  class=\"readonly\">\r\n");
	for (int i=1; i<=count; i++) {
		out.print("<td>");
		out.print(rs.getString(i));
		out.print("</td>");
	}
	out.print("<td>");
	out.print("<input type=checkbox name=select checked=true");
	out.print("</td>");
	out.println("</tr>");
	//for(int i=0;i<rscount;i++){
		vid[j]=rs.getInt(1);
		j++;
	//}
			}	

	}
if ("Recover".equalsIgnoreCase(act)&& value3!=null &&vfdate !=null && vtdate!=null ) {
	reccount=stmt2.executeUpdate("truncate table messages_in");
	for(int j=0;j<rscount;j++){
		query="select packet_recovery("+vid[j]+")";
		//out.println(query);
		rs1=stmt2.executeQuery(query);
	}
	reccount=stmt2.executeUpdate("insert into ozekimessageout(receiver,msg,status,receivedtime,operator)  select distinct phone_no,message,'send',now(), operator from messages_in");
	
      out.write("\r\n");
      out.write("<tr class=\"readonly\" align=\"center\"><td colspan=\"6\">Recovery Initiated for missing packets. check the logs if messages has been submited </td></tr>	\r\n");
 }  
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("</td></tr>\r\n");
      out.write("</table>\r\n");

rs.close();

      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
