/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.91
 * Generated at: 2025-01-08 11:48:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.io.*;
import java.text.*;
import java.util.*;
import com.locationDao;
import com.locationBean;
import com.datapacketsDao;
import com.datapacketsBean;

public final class packets_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(10);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.text");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("com.locationDao");
    _jspx_imports_classes.add("com.locationBean");
    _jspx_imports_classes.add("com.datapacketsDao");
    _jspx_imports_classes.add("com.datapacketsBean");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      com.locationBean obj = null;
      obj = (com.locationBean) _jspx_page_context.getAttribute("obj", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (obj == null){
        obj = new com.locationBean();
        _jspx_page_context.setAttribute("obj", obj, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("obj"), request);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      com.datapacketsBean objDP = null;
      objDP = (com.datapacketsBean) _jspx_page_context.getAttribute("objDP", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (objDP == null){
        objDP = new com.datapacketsBean();
        _jspx_page_context.setAttribute("objDP", objDP, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("objDP"), request);
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

locationDao location = new locationDao();
datapacketsDao dp = new datapacketsDao();

String value1=request.getParameter("value1");
String value2=request.getParameter("value2");
String value3=request.getParameter("value3");
String value4=request.getParameter("value4");
String search=request.getParameter("search");
if (search==null){search="0";}

if (!search.equalsIgnoreCase("0")){
	obj.setLocation_id(Integer.parseInt(search));
	locationDao loc = new locationDao();
	loc.searchLocation(obj);
	int Location_id=obj.getLocation_id();
	String Lname=obj.getLname();
		value1=String.valueOf(obj.getStateid());
		value2=String.valueOf(obj.getDistrict_id());
		value3=String.valueOf(obj.getCounty_id());
		value4=String.valueOf(obj.getLocation_id());
	}


if (value1==null){value1="0";}
if (value2==null){value2="0";}
if (value3==null){value3="0";}
if (value4==null){value4="0";}
if (!value4.equalsIgnoreCase("0")){search=value4;}



String vfdate=request.getParameter("vfdate");
String vtdate=request.getParameter("vtdate");

DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
String formattedDate = df.format(new java.util.Date());
//out.println(formattedDate);

if(vfdate == null){ 
 vfdate=formattedDate;
 vtdate=formattedDate;
}



      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Reports</title>\r\n");
      out.write("\r\n");
      out.write("<link href=\"../styles/text.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"../Script/datepicker.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function parameter(){\r\n");
      out.write("var vid1 = document.getElementById(\"state\").value\r\n");
      out.write("		if (vid1==null || vid1==\"\"){vid1=0;}\r\n");
      out.write("var vid2 = document.getElementById(\"district\").value\r\n");
      out.write("		if (vid2==null || vid2==\"\"){vid2=0;}\r\n");
      out.write("var vid3 = document.getElementById(\"county\").value\r\n");
      out.write("		if (vid3==null || vid3==\"\"){vid3=0;}\r\n");
      out.write("var vid4 = document.getElementById(\"location\").value\r\n");
      out.write("		if (vid4==null || vid4==\"\"){vid4=0;}\r\n");
      out.write("var vfdate= document.getElementById(\"fdate\").value\r\n");
      out.write("var vtdate= document.getElementById(\"tdate\").value\r\n");
      out.write("window.location.replace(\"packets.jsp?value1=\"+vid1+\"&&value2=\"+vid2+\"&&value3=\"+vid3+\"&&value4=\"+vid4+\"&&vfdate=\"+vfdate+\"&&vtdate=\"+vtdate);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function search(){\r\n");
      out.write("var vid1 = document.getElementById(\"txtSearch\").value\r\n");
      out.write("var vfdate= document.getElementById(\"fdate\").value\r\n");
      out.write("var vtdate= document.getElementById(\"tdate\").value\r\n");
      out.write("window.location.replace(\"packets.jsp?search=\"+vid1+\"&&vfdate=\"+vfdate+\"&&vtdate=\"+vtdate);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	  \r\n");
      out.write("<table width=\"100%\">\r\n");
      out.write("<tr>\r\n");
      out.write("	<td width=\"10%\" VALIGN=TOP>\r\n");
      out.write("	<table width=\"10%\" class=\"border\" >\r\n");
      out.write("		<tr><td class=\"Blue-content\" colspan=\"4\"><b>Select Date Range</b></td></tr>\r\n");
      out.write("		<tr><td class=\"content style1\" align=\"right\"><b>From</b></td>\r\n");
      out.write("		<td><input id=\"fdate\"  class=\"content style1\" type=\"text\" name=\"fdate\" size=\"10\" maxlength=\"12\" value=");
      out.print(vfdate);
      out.write(">\r\n");
      out.write("		<a href=\"javascript:NewCal('fdate','ddmmyyyy',false)\"><img src=\"../images/calendar.JPG\" width=\"16\" height=\"16\" border=\"0\" alt=\"Pick a date\"></a></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr><td class=\"content style1\" align=\"right\"><b>To</b></td>\r\n");
      out.write("		<td><input id=\"tdate\"  class=\"content style1\" type=\"text\" name=\"tdate\" size=\"10\" maxlength=\"12\" value=");
      out.print(vtdate);
      out.write(">\r\n");
      out.write("		<a href=\"javascript:NewCal('tdate','ddmmyyyy',false)\"><img src=\"../images/calendar.JPG\" width=\"16\" height=\"16\" border=\"0\" alt=\"Pick a date\"></a></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr><td class=\"Blue-content\" colspan=\"6\" align=\"left\">Select Station</td></tr>\r\n");
      out.write("		<tr><td class=\"content style1\"><b> StationID </b></td><td><input type=text id=txtSearch name=txtSearch  class=\"content style1\" value=\"");
      out.print(search);
      out.write("\" size=\"5\">\r\n");
      out.write("		<input class=\"content style1\" type=\"submit\" value=\"Search\" onClick=\"search()\"></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("\r\n");
      out.write("		<tr><td class=\"content style1\"><b> State </b></td>\r\n");
      out.write("			<td>\r\n");
      out.write("				<select id=\"state\" onchange=\"parameter()\" class=\"content style1\">\r\n");
      out.write("				<option value=\"0\">--Please Select--</option>\r\n");
      out.write("					");
 
					List<locationBean> list1 =location.viewStates();
					Iterator<locationBean> S = list1.iterator(); 
					while (S.hasNext()) {
					obj = (locationBean)S.next();
					
      out.write("\r\n");
      out.write("					<option value=\"");
      out.print(obj.getStateid());
      out.write('"');
      out.write('>');
      out.print(obj.getSname());
      out.write("</option>\r\n");
      out.write("					");
 if(obj.getStateid()==Integer.parseInt(value1)){
      out.write("\r\n");
      out.write("					<option value=\"");
      out.print(value1);
      out.write("\" selected >");
      out.print(obj.getSname());
      out.write("</option> \r\n");
      out.write("					");
} 
							}
      out.write("\r\n");
      out.write("				</select>\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("\r\n");
      out.write("		<tr><td class=\"content style1\"><b> District</b> </td>\r\n");
      out.write("			<td>\r\n");
      out.write("				<select id=\"district\" onchange=\"parameter()\" class=\"content style1\">\r\n");
      out.write("				<option value=\"0\">--Please Select--</option>\r\n");
      out.write("							");
 
							List<locationBean> list2 =location.viewDistrict(Integer.parseInt(value1));
							Iterator<locationBean> D = list2.iterator(); 
							while (D.hasNext()) {
							obj = (locationBean)D.next();
							
      out.write("\r\n");
      out.write("							<option value=\"");
      out.print(obj.getDistrict_id());
      out.write('"');
      out.write(' ');
      out.write('>');
      out.print(obj.getDname());
      out.write("</option>\r\n");
      out.write("							");
 if(obj.getDistrict_id()==Integer.parseInt(value2)){
      out.write("\r\n");
      out.write("							<option value=\"");
      out.print(value2);
      out.write("\" selected >");
      out.print(obj.getDname());
      out.write("</option>\r\n");
      out.write("							");
}
									}
      out.write("\r\n");
      out.write("				\r\n");
      out.write("				</select>\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("\r\n");
      out.write("		<tr><td class=\"content style1\"><b>Mandal</b> </td>\r\n");
      out.write("			<td>\r\n");
      out.write("				<select id=\"county\" onchange=\"parameter()\" class=\"content style1\">\r\n");
      out.write("				<option value=\"0\">--Please Select--</option>\r\n");
      out.write("				");

							List<locationBean> list3 =location.viewCounty(Integer.parseInt(value2));
							Iterator<locationBean> C = list3.iterator(); 
							while (C.hasNext()) {
								obj = (locationBean)C.next();
							
      out.write("\r\n");
      out.write("						<option value=\"");
      out.print(obj.getCounty_id());
      out.write('"');
      out.write(' ');
      out.write('>');
      out.print(obj.getCname());
      out.write("</option>\r\n");
      out.write("						");
 if(obj.getCounty_id()==Integer.parseInt(value3)){
      out.write("\r\n");
      out.write("						<option value=\"");
      out.print(value3);
      out.write("\" selected >");
      out.print(obj.getCname());
      out.write("</option>\r\n");
      out.write("						");
}
						}
      out.write("\r\n");
      out.write("				\r\n");
      out.write("				</select>\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("\r\n");
      out.write("		<tr><td class=\"content style1\"><b> Stations</b> </td>\r\n");
      out.write("			<td>\r\n");
      out.write("				<select id=\"location\" onchange=\"parameter()\" class=\"content style1\" size=\"20\">\r\n");
      out.write("					<option value=\"0\">--Please Select--</option>\r\n");
      out.write("					");

							List<locationBean> list4;		
							
							if(value3.equalsIgnoreCase("0")) {
								list4 =location.viewStations(Integer.parseInt(value1),Integer.parseInt(value2));
								}
							else{
								list4 =location.viewStations(Integer.parseInt(value1),Integer.parseInt(value2),Integer.parseInt(value3));
								}	
								Iterator<locationBean> V = list4.iterator(); 
								while (V.hasNext()) {
									obj = (locationBean)V.next();
								
      out.write("\r\n");
      out.write("							<option value=\"");
      out.print(obj.getLocation_id());
      out.write('"');
      out.write(' ');
      out.write('>');
      out.print(obj.getLname());
      out.write("</option>\r\n");
      out.write("							");
 if(obj.getLocation_id()==Integer.parseInt(value4)){
      out.write("\r\n");
      out.write("							<option value=\"");
      out.print(value3);
      out.write("\" selected >");
      out.print(obj.getLname());
      out.write("</option>\r\n");
      out.write("							");
}
							}
      out.write("\r\n");
      out.write("					\r\n");
      out.write("				</select>\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("	</table>\r\n");
      out.write("	</td>\r\n");
      out.write("	<td valign=top>\r\n");
      out.write("		<table width=\"100%\" border=\"1\" cellpadding=\"0\" cellspacing=\"0\" id=\"stretch\" > \r\n");
      out.write("			<tr><td class=\"Blue-content\">Date Time</td>\r\n");
      out.write("				<td class=\"Blue-content\">Rain (mm)</td><td class=\"Blue-content\">Temparature(&ordm; C)</td><td class=\"Blue-content\">Wind</td>\r\n");
      out.write("				<td class=\"Blue-content\">Wind<br> Direction</td><td class=\"Blue-content\">Humidity</td><td class=\"Blue-content\">Local Pressure</td><td class=\"Blue-content\">MSLP</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			");
 
			if(!value4.equalsIgnoreCase("0")) {
				Float vrain  = null;
				Float vtemp  = null;
				Float vwind  = null;
				Float vwind_direction  = null;
				Float vhumidity  = null;
				Float vlocal_pressure  = null;
				Float vmslp  = null;
				
			List<datapacketsBean> listP = dp.viewPackets(Integer.parseInt(value4), vfdate, vtdate);
						Iterator<datapacketsBean> DP = listP.iterator(); 
					while (DP.hasNext()) {
					objDP = (datapacketsBean)DP.next();
					vrain = objDP.getRain();
					vtemp = objDP.getTemp();
					vwind = objDP.getWind();
					vwind_direction = objDP.getWind_direction();
					vhumidity = objDP.getHumidity();
					vlocal_pressure = objDP.getLocal_pressure();
					vmslp = objDP.getMslp();
					
			
      out.write("\r\n");
      out.write("			<tr>\r\n");
      out.write("		<!-- <td class=\"readonly\"><a href=\"packetedit.jsp?v1=");
      out.print(objDP.getStation_id());
      out.write("&&v2=");
      out.print(objDP.getPacketno());
      out.write("&&v3=");
      out.print(objDP.getDtime());
      out.write("\" target=\"_blank\" class=\"Blue-content\">");
      out.print(objDP.getDtime());
      out.write("</a></td>\r\n");
      out.write("		 -->\r\n");
      out.write("				<td class=\"readonly\" class=\"Blue-content\">");
      out.print(objDP.getDtime());
      out.write("</td>\r\n");
      out.write("				<td class=\"readonly\">");
 if (vrain == null){ 
      out.write('N');
      out.write('/');
      out.write('A');
} else {
      out.print(vrain);
}
      out.write("</td>\r\n");
      out.write("				<td class=\"readonly\">");
 if (vtemp == null){ 
      out.write('N');
      out.write('/');
      out.write('A');
} else {
      out.print(vtemp);
}
      out.write("</td>\r\n");
      out.write("				<td class=\"readonly\">");
 if (vtemp == null){ 
      out.write('N');
      out.write('/');
      out.write('A');
} else {
      out.print(vtemp);
}
      out.write("</td>\r\n");
      out.write("				<td class=\"readonly\">");
 if (vwind == null){ 
      out.write('N');
      out.write('/');
      out.write('A');
} else {
      out.print(vwind);
}
      out.write("</td>\r\n");
      out.write("				<td class=\"readonly\">");
 if (vhumidity == null){ 
      out.write('N');
      out.write('/');
      out.write('A');
} else {
      out.print(vhumidity);
}
      out.write("</td>\r\n");
      out.write("				<td class=\"readonly\">");
 if (vlocal_pressure == null){ 
      out.write('N');
      out.write('/');
      out.write('A');
} else {
      out.print(vlocal_pressure);
}
      out.write("</td>\r\n");
      out.write("				<td class=\"readonly\">");
 if (vmslp == null){ 
      out.write('N');
      out.write('/');
      out.write('A');
} else {
      out.print(vmslp);
}
      out.write("</td>\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("			</tr>\r\n");
      out.write("				");
} 
					}
      out.write("\r\n");
      out.write("		</table>\r\n");
      out.write("	</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("  \r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
