/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.91
 * Generated at: 2025-01-02 05:10:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import com.ConnectionProvider;

public final class StationConfig_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


Connection con=null;
ResultSet rs=null;
Statement stmt=null;
String query="";
int cid;

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.ConnectionProvider");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function stn(){\r\n");
      out.write("var vid1 = document.getElementById(\"state\").value\r\n");
      out.write("	if (vid1==null || vid1==\"\"){vid1=0;}\r\n");
      out.write("var vid2 = document.getElementById(\"district\").value\r\n");
      out.write("	if (vid2==null || vid2==\"\"){vid2=0;}\r\n");
      out.write("var vid3 = document.getElementById(\"county\").value\r\n");
      out.write("	if (vid3==null || vid3==\"\"){vid3=0;}\r\n");
      out.write("var vid4 = document.getElementById(\"location\").value\r\n");
      out.write("	if (vid4==null || vid4==\"\"){vid4=0;}\r\n");
      out.write("window.location.replace(\"StationConfig.jsp?value1=\"+vid1+\"&&value2=\"+vid2+\"&&value3=\"+vid3+\"&&value4=\"+vid4);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function updatestn(){\r\n");
      out.write("var vid4 = document.getElementById(\"location\").value\r\n");
      out.write("		if (vid4==null || vid4==\"\"){\r\n");
      out.write("	vid4 = document.getElementById(\"txtSearch\").value}\r\n");
      out.write("window.location.replace(\"updatestation.jsp?lid=\"+vid4+\"&&action=update\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function addstn(){\r\n");
      out.write("var vid1 = document.getElementById(\"state\").value\r\n");
      out.write("var vid2 = document.getElementById(\"district\").value\r\n");
      out.write("var vid3 = document.getElementById(\"county\").value\r\n");
      out.write("var vid4 = document.getElementById(\"location\").value\r\n");
      out.write("\r\n");
      out.write("if (vid1==0){\r\n");
      out.write("	alert(\"Please select State\");\r\n");
      out.write("	window.location.replace(\"StationConfig.jsp\");\r\n");
      out.write("	} \r\n");
      out.write("else {\r\n");
      out.write("	if (vid2==0){\r\n");
      out.write("		alert(\"Please select District\");\r\n");
      out.write("		window.location.replace(\"StationConfig.jsp?value1=\"+vid1);\r\n");
      out.write("				}\r\n");
      out.write("	else{\r\n");
      out.write("		if (vid3==0){\r\n");
      out.write("		alert(\"Please select Mandal\");\r\n");
      out.write("		window.location.replace(\"StationConfig.jsp?value1=\"+vid1+\"&&value2=\"+vid2);\r\n");
      out.write("				}\r\n");
      out.write("		else{\r\n");
      out.write("			window.location.replace(\"updatestation.jsp?value1=\"+vid1+\"&&value2=\"+vid2+\"&&value3=\"+vid3+\"&&action=add\");\r\n");
      out.write("		}\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function search(){\r\n");
      out.write("var vid1 = document.getElementById(\"txtSearch\").value\r\n");
      out.write("window.location.replace(\"StationConfig.jsp?search=\"+vid1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');

String value1=request.getParameter("value1");
String value2=request.getParameter("value2");
String value3=request.getParameter("value3");
String value4=request.getParameter("value4");
String search=request.getParameter("search");





con = ConnectionProvider.getCon();
stmt=con.createStatement();




if (search!=null){
query="select clientid,state,district,county,location from station_configs_det where clientid='"+search+"'";	
	rs=stmt.executeQuery(query);
	while(rs.next()){
		value1=rs.getString("state");
		value2=rs.getString("district");
		value3=rs.getString("county");
		value4=rs.getString("clientid");
	}
}

if (value1==null){value1="0";}
if (value2==null){value2="0";}
if (value3==null){value3="0";}
if (value4==null){value4="0";}
if (search==null){search="0";}

rs = stmt.executeQuery("select param_id as sid,group_value as state from parameter where active='Y' and group_family='LOCATION' and Group_name='STATE'");

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link href=\"../styles/text.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" id=\"stretch\"  bgcolor=\"#DBEBFF\">\r\n");
      out.write("<tr><td width=\"10%\" VALIGN=TOP>\r\n");
      out.write("  <table width=\"10%\" border=\"0\" class=border cellpadding=\"1\"  bgcolor=\"#DBEBFF\" VALIGN=TOP>\r\n");
      out.write("	<tr><td class=\"Blue-content\" colspan=\"6\" align=\"center\">Station Details</td></tr>\r\n");
      out.write("	<tr><td class=\"content style1\"> StationID </td>\r\n");
      out.write("	<td><input type=text name=txtSearch  class=\"content style1\" value=\"");
      out.print(search);
      out.write("\" size=\"5\">\r\n");
      out.write("	<input class=\"content style1\" type=\"submit\" value=\"Search\" onClick=\"search()\"></td>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<tr><td class=\"content style1\"> State </td>\r\n");
      out.write("	<td>\r\n");
      out.write("	<select id=\"state\" onchange=\"stn()\" class=\"content style1\">\r\n");
      out.write("	<option value=\"0\">--Please Select--</option>\r\n");
      out.write("	");
 while(rs.next()){ 
      out.write("\r\n");
      out.write("	<option value=\"");
      out.print(rs.getInt("sid"));
      out.write('"');
      out.write('>');
      out.print(rs.getString("state"));
      out.write("</option>\r\n");
      out.write("	");
 if(rs.getString("sid").equals(value1)){
      out.write("\r\n");
      out.write("	<option value=\"");
      out.print(value1);
      out.write("\" selected disabled>");
      out.print(rs.getString("state"));
      out.write("</option> \r\n");
      out.write("	");

	}
	}
	
      out.write("\r\n");
      out.write("	</select> </td></tr>\r\n");
      out.write("	<tr><td class=\"content style1\"> District </td><td>\r\n");
      out.write("	<select id=\"district\" onchange=\"stn()\" class=\"content style1\">\r\n");
      out.write("	<option value=\"0\">--Please Select--</option>\r\n");
      out.write("	");

	rs=stmt.executeQuery("select param_id as did,group_value as district from parameter where active='Y' and group_family='LOCATION' and Group_name='DISTRICT' and parent_group='"+value1+"'");
	while(rs.next()){
	
      out.write("\r\n");
      out.write("	<option value=\"");
      out.print(rs.getInt("did"));
      out.write('"');
      out.write(' ');
      out.write('>');
      out.print(rs.getString("district"));
      out.write("</option>\r\n");
      out.write("	");
 if(rs.getString("did").equals(value2)){
      out.write("\r\n");
      out.write("	<option value=\"");
      out.print(value2);
      out.write("\" selected disabled>");
      out.print(rs.getString("district"));
      out.write("</option>\r\n");
      out.write("	");

	}
	}
	
      out.write("\r\n");
      out.write("	</select>\r\n");
      out.write("	</td></tr>\r\n");
      out.write("\r\n");
      out.write("	<tr><td class=\"content style1\"> Mandal/Taluq </td><td>\r\n");
      out.write("	<select id=\"county\" onchange=\"stn()\" class=\"content style1\">\r\n");
      out.write("	<option value=\"0\">--Please Select--</option>\r\n");
      out.write("	");

		rs=stmt.executeQuery("select param_id as cid,group_value as county from parameter where group_family='LOCATION' and Group_name='COUNTY' and parent_group='"+value2+"' order by 2");
	while(rs.next()){
	
      out.write("\r\n");
      out.write("	<option value=\"");
      out.print(rs.getInt("cid"));
      out.write('"');
      out.write(' ');
      out.write('>');
      out.print(rs.getString("county"));
      out.write("</option>\r\n");
      out.write("	");
 if(rs.getString("cid").equals(value3)){
      out.write("\r\n");
      out.write("	<option value=\"");
      out.print(value3);
      out.write("\" selected disabled>");
      out.print(rs.getString("county"));
      out.write("</option>\r\n");
      out.write("	");

	}
	}
		
      out.write("\r\n");
      out.write("	</select> </td></tr>\r\n");
      out.write("	");

	
	query="select *from station_configs_det ";
		if(value3.equalsIgnoreCase("0")) {
				query=query+" where state="+value1+" and district="+value2+" order by location";
					}
				else{
								query=query+" where state="+value1+" and district="+value2+" and county="+value3+" order by location";
				}
rs=stmt.executeQuery(query);

	
      out.write("\r\n");
      out.write("	<tr><td class=\"content style1\"> Stations / Locations </td>\r\n");
      out.write("	<td class=\"content style1\" align=\"left\"  >\r\n");
      out.write("	<select id=\"location\" onchange=\"stn()\" class=\"content style1\" size=\"20\">\r\n");
      out.write("	<option value=\"0\">--Please Select--</option>\r\n");
      out.write("	");
 while(rs.next()){ 
      out.write("\r\n");
      out.write("	<option value=\"");
      out.print(rs.getInt("clientid"));
      out.write('"');
      out.write(' ');
      out.write('>');
      out.print(rs.getString("location"));
      out.write("</option>\r\n");
      out.write("	");
 if(rs.getString("clientid").equals(value4)){
      out.write("\r\n");
      out.write("	<option value=\"");
      out.print(value4);
      out.write("\" selected disabled>");
      out.print(rs.getString("location"));
      out.write("</option>\r\n");
      out.write("	");
} } 
      out.write("\r\n");
      out.write("	</select> </td></tr>\r\n");
      out.write("	<tr><td colspan=\"2\" align=\"center\"><input type=\"submit\" name=\"operation1\" onclick=\"addstn()\" value=\"Add New\" ></td></tr>\r\n");
      out.write("  </table>\r\n");
      out.write("  </td>\r\n");
      out.write("\r\n");
      out.write("	");

	query="select *, to_char(last_reported,'DD/MM/YYYY HH24:MI') as last_signal,(select group_value from parameter where  param_id=district) as dt_name,(select group_value from parameter where  param_id=county) as ct_name  from station_configs_det";

	if ("0".equalsIgnoreCase(search)){
				query=query+" where clientid="+value4; 
				}
	else {query=query+" where clientid='"+search+"'";
				}
		
	rs=stmt.executeQuery(query);
	while(rs.next()){ 
      out.write("\r\n");
      out.write("			<input type=hidden name=\"lid\" value=\"");
      out.print(rs.getString("clientid"));
      out.write("\" >\r\n");
      out.write("  \r\n");
      out.write("  <td width=\"80%\" VALIGN=TOP>\r\n");
      out.write("	<table width=\"100%\" border=\"0\" class=border cellpadding=\"4\" cellspacing=\"4\" bgcolor=\"\" VALIGN=TOP>\r\n");
      out.write("		<tr><td class=\"Blue-content\">ID</td><td class=\"readonly\">");
      out.print(rs.getString("clientid"));
      out.write("</td>\r\n");
      out.write("		<td class=\"Blue-content\">District</td><td class=\"readonly\">");
      out.print(rs.getString("dt_name"));
      out.write("</td>\r\n");
      out.write("		<td class=\"Blue-content\">Mandal</td><td class=\"readonly\">");
      out.print(rs.getString("ct_name"));
      out.write("</td></tr>\r\n");
      out.write("		<tr><td class=\"Blue-content\">Location</td><td class=\"readonly\">");
      out.print(rs.getString("location"));
      out.write("</td>	\r\n");
      out.write("		<td class=\"Blue-content\">Location Address</td><td class=\"readonly\"  colspan=\"1\">");
      out.print(rs.getString("address"));
      out.write("</td>\r\n");
      out.write("		<td class=\"Blue-content\">Datum</td><td class=\"readonly\">");
      out.print(rs.getString("wmsl"));
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("		<tr><td class=\"Blue-content\">Longitude (Degrees)</td><td class=\"readonly\">");
      out.print(rs.getString("Longitude"));
      out.write("</td>\r\n");
      out.write("		<td class=\"Blue-content\">Latitude (Degrees)</td><td class=\"readonly\">");
      out.print(rs.getString("Latitude"));
      out.write("</td>\r\n");
      out.write("		<td class=\"Blue-content\">Altitude (meters)</td><td class=\"readonly\">");
      out.print(rs.getString("Altitude"));
      out.write("</td></tr>\r\n");
      out.write("		<tr><td class=\"Blue-content\">Station SIM #</td><td class=\"readonly\">");
      out.print(rs.getString("stn_sim"));
      out.write("</td>\r\n");
      out.write("		<td class=\"Blue-content\">Data Frequency (minutes)</td><td class=\"readonly\">");
      out.print(rs.getString("datafreq"));
      out.write("</td>\r\n");
      out.write("		<td class=\"Blue-content\">Comm Frequency (minutes)</td><td class=\"readonly\">");
      out.print(rs.getString("commfreq"));
      out.write("</td></tr>\r\n");
      out.write("		<tr><td class=\"Blue-content\">Sensor Height</td><td class=\"readonly\">");
      out.print(rs.getString("mslpoint1"));
      out.write("</td>\r\n");
      out.write("		<td class=\"Blue-content\">Rain Calibration</td><td class=\"readonly\">");
      out.print(rs.getString("calibrationrain"));
      out.write("</td>\r\n");
      out.write("		<td class=\"Blue-content\">Wind Calibration</td><td class=\"readonly\">");
      out.print(rs.getString("calibrationwind"));
      out.write("</td></tr>\r\n");
      out.write("		<tr><td class=\"Blue-content\">Server SIM</td><td class=\"readonly\">");
      out.print(rs.getString("srv_sim"));
      out.write("</td>\r\n");
      out.write("		<td class=\"Blue-content\">Server Backup SIM1</td><td class=\"readonly\">");
      out.print(rs.getString("srv_sim_bkp1"));
      out.write("</td>\r\n");
      out.write("		<td class=\"Blue-content\">Server Backup SIM2</td><td class=\"readonly\">");
      out.print(rs.getString("srv_sim_bkp2"));
      out.write("</td></tr>\r\n");
      out.write("		<!-- <tr><td class=\"Blue-content\">Time 1 (HHMM)</td><td class=\"readonly\">");
      out.print(rs.getString("paramtime1"));
      out.write("</td>\r\n");
      out.write("		<td class=\"Blue-content\">Time 2 (HHMM)</td><td class=\"readonly\">");
      out.print(rs.getString("paramtime2"));
      out.write("</td>\r\n");
      out.write("		<td class=\"Blue-content\">Time 3 (HHMM)</td><td class=\"readonly\">");
      out.print(rs.getString("paramtime3"));
      out.write("</td></tr>\r\n");
      out.write("		<tr><td class=\"Blue-content\">Future Expansion</td><td class=\"readonly\">");
      out.print(rs.getString("futureexpansion"));
      out.write("</td>\r\n");
      out.write("		<td class=\"Blue-content\">Num Settings</td><td class=\"readonly\">");
      out.print(rs.getString("numsettings"));
      out.write("</td>\r\n");
      out.write("		<td class=\"Blue-content\">Numbers</td><td class=\"readonly\">");
      out.print(rs.getString("phnumbers"));
      out.write("</td></tr>\r\n");
      out.write("		<tr><td class=\"Blue-content\">Activate</td><td class=\"readonly\">");
      out.print(rs.getString("activate"));
      out.write("</td>\r\n");
      out.write("		<td class=\"Blue-content\">Watchdog</td><td class=\"readonly\">");
      out.print(rs.getString("Watchdog"));
      out.write("</td>\r\n");
      out.write("		<td class=\"Blue-content\">Flash</td><td class=\"readonly\">");
      out.print(rs.getString("flash"));
      out.write("</td></tr> -->\r\n");
      out.write("		<tr><td class=\"Blue-content\">Contact Person</td><td class=\"readonly\">");
      out.print(rs.getString("contact_person"));
      out.write("</td>\r\n");
      out.write("		<td class=\"Blue-content\">Contact Phone</td><td class=\"readonly\">\r\n");
      out.write("			<textarea readonly rows=\"4\" cols=\"40\" class=\"readonly\" name=\"txtPhone\" >");
      out.print(rs.getString("contact_phone"));
      out.write("</textarea> </td>\r\n");
      out.write("		<td class=\"Blue-content\">Email</td><td>\r\n");
      out.write("			<textarea readonly rows=\"4\" cols=\"50\" class=\"readonly\" name=\"txtEmail\" >");
      out.print(rs.getString("emailid"));
      out.write("</textarea> </td></tr>\r\n");
      out.write("		<tr><td class=\"Blue-content\">Last Reported</td><td class=\"readonly\" colspan=1>");
      out.print(rs.getString("last_signal"));
      out.write("</td>\r\n");
      out.write("		<td class=\"Blue-content\">SIM Operator</td><td class=\"readonly\" colspan=1>");
      out.print(rs.getString("operator"));
      out.write("</td>\r\n");
      out.write("		<td class=\"Blue-content\">Client Alias</td><td class=\"readonly\" colspan=1>");
      out.print(rs.getString("client_alias"));
      out.write("</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr><td><a href=\"http://maps.google.com/maps?q=");
      out.print(rs.getString("Latitude"));
      out.write(',');
      out.print(rs.getString("Longitude"));
      out.write("\" target=\"_blank\"><img  src=\"../images/googlemaps.png\" alt=\"Show location on Google Maps\"/> </a></td>\r\n");
      out.write("		<tr><td colspan=\"4\" align=\"center\"><input type=\"submit\" name=\"operation2\" onclick=\"updatestn()\" value=\"Edit\" ></td></tr>\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("	</table>\r\n");
      out.write("  </td></tr>\r\n");

}

      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
