/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.91
 * Generated at: 2024-09-26 05:00:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import com.ConnectionProvider;

public final class stnlist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


Connection con=null;
ResultSet rs=null;
Statement stmt=null;


  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.ConnectionProvider");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write(" \n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- Sesssion Management -->\n");
if(null == session.getAttribute("theName")){  
  // User is not logged in.
  out.println("your Session has expired");
  response.sendRedirect("../index.html?invalid=0");
}

      out.write("\n");
      out.write("<!-- End of Sesssion Management -->\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<TITLE> Station Statistics </TITLE>\n");
      out.write("<link href=\"../styles/text.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");

con = ConnectionProvider.getCon();
stmt=con.createStatement();
String value1=request.getParameter("v1");

      out.write("\n");
      out.write("<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" id=\"stretch\"> \n");
      out.write("<tr height=\"100%\" valign=\"center\"> \n");
      out.write("<td colspan=\"2\" valign=\"center\" height=\"100%\">\n");
      out.write("	<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"#FFFFFF\"> \n");
      out.write("		<tr><td height=\"100%\" align=\"left\" valign=\"bottom\" scope=\"col\">\n");
      out.write("		<!-- <a href=\"#\"> -->\n");
      out.write("		<img src=\"../images/Logo.png\" width=\"100\" height=\"100\">\n");
      out.write("		<!-- </a> -->\n");
      out.write("		</td></tr>\n");
      out.write("		<tr><td background=\"../images/Logo_bottom.jpg\" scope=\"col\"><img src=\"../images/Logo_bottom.jpg\" width=\"3\" height=\"4\"></td></tr>\n");
      out.write("	</table>\n");
      out.write("</td>\n");
      out.write("</table>\n");
      out.write("<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"5\" id=\"stretch\" >\n");
      out.write("\n");
      out.write("\n");
      out.write("<tr><td></td></tr>\n");
      out.write("\n");


if(value1.equalsIgnoreCase("t")) {
rs=stmt.executeQuery("select a.clientid,(select group_value from parameter where param_id=a.state) as state,(select group_value from parameter where param_id=a.district) as district,coalesce((select group_value from parameter where param_id=a.county),null,'N/A') as county, a.location,a.longitude,a.latitude, coalesce(to_char((last_reported),'MM/DD/YYYY HH24:MI'),null,'-') as packet_date from station_configs_det as a where activate!=0 ");

      out.write("\n");
      out.write("<tr><td class=\"Blue-content\" align=\"center\" colspan=\"2\">All Stations List</td></tr>\n");

}
if(value1.equalsIgnoreCase("w")) {
rs=stmt.executeQuery("select a.clientid,(select group_value from parameter where param_id=a.state) as state,(select group_value from parameter where param_id=a.district) as district,coalesce((select group_value from parameter where param_id=a.county),null,'N/A') as county,a.location,a.longitude,a.latitude,coalesce(to_char((last_reported),'MM/DD/YYYY HH24:MI'),null,'-') as packet_date from station_configs_det as a where activate!=0 and a.clientid  in (select distinct clientid from data_packets where packet_date >= CURRENT_TIMESTAMP - INTERVAL '12 HOUR') and clientid!=15000");

      out.write("\n");
      out.write("<tr><td class=\"Blue-content\" align=\"center\" colspan=\"2\">Working Stations List</td></tr>\n");

}
if(value1.equalsIgnoreCase("n")) {
rs=stmt.executeQuery("select a.clientid,(select group_value from parameter where param_id=a.state) as state,(select group_value from parameter where param_id=a.district) as district, coalesce((select group_value from parameter where param_id=a.county),null,'N/A') as county,a.location,a.longitude,a.latitude, coalesce(to_char((last_reported),'MM/DD/YYYY HH24:MI'),null,'-') as packet_date from station_configs_det as a where activate!=0 and a.clientid not in (select distinct clientid from data_packets where packet_date >= CURRENT_TIMESTAMP - INTERVAL '12 HOUR'and clientid!=15000) order by district,packet_date");

      out.write("\n");
      out.write("<tr>\n");
      out.write("<td align=\"center\" class=\"Blue-content\">\n");
      out.write("		<script type=\"text/javascript\">\n");
      out.write("			var currentTime = new Date()\n");
      out.write("			var month = currentTime.getMonth() + 1\n");
      out.write("			var day = currentTime.getDate()\n");
      out.write("			var year = currentTime.getFullYear()\n");
      out.write("			var hour = currentTime.getHours()\n");
      out.write("			var minute = currentTime.getMinutes()\n");
      out.write("			document.write(\"Not Working Stations List as on : \"+day + \"/\" + month + \"/\" + year)\n");
      out.write("		</script>\n");
      out.write("		</td>\n");
      out.write("</tr>\n");

}

      out.write("\n");
      out.write("\n");
      out.write("<table width=\"90%\" class=\"border\" border=\"0\" cellpadding=\"0\" cellspacing=\"5\" id=\"stretch\" >\n");
      out.write("<tr><td class=\"Blue-content\">clientid</td><td class=\"Blue-content\">State</td><td class=\"Blue-content\">District</td>\n");
      out.write("<td class=\"Blue-content\">Mandal</td><td class=\"Blue-content\">Location</td><td class=\"Blue-content\">Longitude</td>\n");
      out.write("<td class=\"Blue-content\">Latitude</td><td class=\"Blue-content\">Data Last Received<br>(mm/dd/yyyy hh24:mi)</td>\n");
      out.write("</tr>\n");

while(rs.next()){ 
      out.write("\n");
      out.write("<tr>\n");
      out.write("<td class=\"readonly\">");
      out.print(rs.getString(1));
      out.write("</td><td class=\"readonly\">");
      out.print(rs.getString(2));
      out.write("</td><td class=\"readonly\">");
      out.print(rs.getString(3));
      out.write("</td>\n");
      out.write("<td class=\"readonly\">");
      out.print(rs.getString(4));
      out.write("</td><td class=\"readonly\">");
      out.print(rs.getString(5));
      out.write("</td><td class=\"readonly\">");
      out.print(rs.getString(6));
      out.write("</td>\n");
      out.write("<td class=\"readonly\">");
      out.print(rs.getString(7));
      out.write("</td><td class=\"readonly\">");
      out.print(rs.getString(8));
      out.write("</td>\n");
      out.write("</tr>\n");

}
rs.close();

      out.write("\n");
      out.write("</table>\n");
      out.write("</table>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
